import type { QuizQuestion } from '@/types/musabaqah'

export const GENERAL_ISLAM_QUESTIONS: QuizQuestion[] = [
  // === 5 PILLARS ===
  {
    id: 'gi-001',
    category: 'general',
    question: 'How many pillars of Islam are there?',
    options: { A: '3', B: '4', C: '5', D: '6' },
    correct: 'C',
    explanation: 'The Five Pillars are: Shahada, Salah, Zakat, Sawm, and Hajj.',
  },
  {
    id: 'gi-002',
    category: 'general',
    question: 'What is the first pillar of Islam?',
    options: { A: 'Shahada (Declaration of Faith)', B: 'Salah (Prayer)', C: 'Zakat (Charity)', D: 'Sawm (Fasting)' },
    correct: 'A',
    explanation: 'The Shahada is the declaration: "There is no god but Allah, and Muhammad ﷺ is His messenger."',
  },
  {
    id: 'gi-003',
    category: 'general',
    question: 'What is the second pillar of Islam?',
    options: { A: 'Zakat', B: 'Salah', C: 'Hajj', D: 'Sawm' },
    correct: 'B',
    explanation: 'Salah (prayer) is the second pillar. Muslims pray five times daily.',
  },
  {
    id: 'gi-004',
    category: 'general',
    question: 'What percentage of savings must a Muslim give as Zakat?',
    options: { A: '5%', B: '10%', C: '1%', D: '2.5%' },
    correct: 'D',
    explanation: 'Zakat is 2.5% of savings that have been held above the nisab threshold for one lunar year.',
  },
  {
    id: 'gi-005',
    category: 'general',
    question: 'What is the fourth pillar of Islam?',
    options: { A: 'Sawm (Fasting)', B: 'Hajj', C: 'Salah', D: 'Shahada' },
    correct: 'A',
    explanation: 'Sawm is the obligatory fast during the month of Ramadan.',
  },
  {
    id: 'gi-006',
    category: 'general',
    question: 'How many times must a Muslim perform Hajj in their lifetime?',
    options: { A: 'Every year', B: 'Three times', C: 'Once if able', D: 'Twice' },
    correct: 'C',
    explanation: 'Hajj is obligatory once in a lifetime for every Muslim who is physically and financially able.',
  },
  {
    id: 'gi-007',
    category: 'general',
    question: 'What does "Shahada" mean?',
    options: { A: 'Prayer', B: 'Testimony / Declaration', C: 'Charity', D: 'Fasting' },
    correct: 'B',
    explanation: 'Shahada means testimony or declaration. It is the declaration of faith in Allah and His messenger.',
  },
  {
    id: 'gi-008',
    category: 'general',
    question: 'In which month is fasting (Sawm) observed?',
    options: { A: 'Muharram', B: 'Sha\'ban', C: 'Dhul-Hijjah', D: 'Ramadan' },
    correct: 'D',
    explanation: 'Muslims fast during the entire month of Ramadan, the ninth month of the Islamic calendar.',
  },
  {
    id: 'gi-009',
    category: 'general',
    question: 'What is the pre-dawn meal before fasting called?',
    options: { A: 'Iftar', B: 'Wudu', C: 'Suhoor', D: 'Tarawih' },
    correct: 'C',
    explanation: 'Suhoor is the pre-dawn meal eaten before the Fajr prayer begins and the fast starts.',
  },
  {
    id: 'gi-010',
    category: 'general',
    question: 'What is the meal used to break the fast at sunset called?',
    options: { A: 'Iftar', B: 'Suhoor', C: 'Eid', D: 'Niyyah' },
    correct: 'A',
    explanation: 'Iftar is the meal to break the fast at sunset. It is Sunnah to break the fast with dates and water.',
  },
  {
    id: 'gi-011',
    category: 'general',
    question: 'Where is Hajj performed?',
    options: { A: 'Madinah', B: 'Jerusalem', C: 'Mecca', D: 'Cairo' },
    correct: 'C',
    explanation: 'Hajj is performed in Mecca, Saudi Arabia, during the month of Dhul-Hijjah.',
  },
  {
    id: 'gi-012',
    category: 'general',
    question: 'What is the walk between the hills of Safa and Marwa during Hajj called?',
    options: { A: 'Tawaf', B: 'Sa\'i', C: 'Wuquf', D: 'Rami' },
    correct: 'B',
    explanation: 'Sa\'i is the walking seven times between Safa and Marwa, commemorating Hajar\'s search for water.',
  },
  {
    id: 'gi-013',
    category: 'general',
    question: 'What is the circling of the Ka\'bah called?',
    options: { A: 'Sa\'i', B: 'Rami', C: 'Tawaf', D: 'Wuquf' },
    correct: 'C',
    explanation: 'Tawaf is the act of circling the Ka\'bah seven times in an anti-clockwise direction.',
  },
  {
    id: 'gi-014',
    category: 'general',
    question: 'What is the charity given at the end of Ramadan called?',
    options: { A: 'Sadaqah', B: 'Zakat al-Fitr', C: 'Waqf', D: 'Khums' },
    correct: 'B',
    explanation: 'Zakat al-Fitr is a mandatory charity given at the end of Ramadan before the Eid prayer.',
  },
  {
    id: 'gi-015',
    category: 'general',
    question: 'What does Zakat purify?',
    options: { A: 'The body', B: 'The home', C: 'One\'s wealth and soul', D: 'The community' },
    correct: 'C',
    explanation: 'Zakat purifies one\'s wealth and soul, and the word "zakat" itself means purification and growth.',
  },

  // === ARTICLES OF FAITH ===
  {
    id: 'gi-016',
    category: 'general',
    question: 'How many articles of faith (Arkan al-Iman) are there in Islam?',
    options: { A: '5', B: '6', C: '7', D: '4' },
    correct: 'B',
    explanation: 'There are six articles of faith: belief in Allah, Angels, Books, Prophets, Day of Judgment, and Divine Decree (Qadar).',
  },
  {
    id: 'gi-017',
    category: 'general',
    question: 'What is the sixth article of faith in Islam?',
    options: { A: 'Belief in Angels', B: 'Belief in the Day of Judgment', C: 'Belief in Divine Decree (Qadar)', D: 'Belief in Books' },
    correct: 'C',
    explanation: 'Qadar (Divine Decree) is the belief that Allah has knowledge of and has decreed all things that occur.',
  },
  {
    id: 'gi-018',
    category: 'general',
    question: 'Which of the following is NOT one of the four holy books mentioned in Islam?',
    options: { A: 'Torah (Tawrat)', B: 'Psalms (Zabur)', C: 'Bible (Injeel)', D: 'Hadith' },
    correct: 'D',
    explanation: 'The four holy books are the Tawrat (Torah), Zabur (Psalms), Injeel (Gospel), and the Quran. The Hadith is not a holy book.',
  },
  {
    id: 'gi-019',
    category: 'general',
    question: 'Who received the Zabur (Psalms)?',
    options: { A: 'Musa', B: 'Isa', C: 'Ibrahim', D: 'Dawud' },
    correct: 'D',
    explanation: 'The Zabur was revealed to Prophet Dawud (David) (peace be upon him).',
  },
  {
    id: 'gi-020',
    category: 'general',
    question: 'What is the Arabic word for faith/belief?',
    options: { A: 'Islam', B: 'Iman', C: 'Ihsan', D: 'Taqwa' },
    correct: 'B',
    explanation: 'Iman means faith or belief. The three dimensions of the religion are Islam, Iman, and Ihsan.',
  },
  {
    id: 'gi-021',
    category: 'general',
    question: 'Which angel is responsible for delivering revelation to the prophets?',
    options: { A: 'Mikail', B: 'Israfil', C: 'Jibreel', D: 'Azrael' },
    correct: 'C',
    explanation: 'Jibreel (Gabriel) is the angel entrusted with delivering Allah\'s revelation to the prophets.',
  },
  {
    id: 'gi-022',
    category: 'general',
    question: 'Which angel is responsible for sustenance and rain?',
    options: { A: 'Jibreel', B: 'Mikail', C: 'Israfil', D: 'Ridwan' },
    correct: 'B',
    explanation: 'Mikail (Michael) is the angel responsible for sustenance, rain, and provisions for creation.',
  },
  {
    id: 'gi-023',
    category: 'general',
    question: 'Which angel will blow the trumpet on the Day of Judgment?',
    options: { A: 'Jibreel', B: 'Mikail', C: 'Azrael', D: 'Israfil' },
    correct: 'D',
    explanation: 'Israfil is the angel who will blow the trumpet (Sur) to signal the Day of Judgment.',
  },
  {
    id: 'gi-024',
    category: 'general',
    question: 'What are the two angels who question the deceased in the grave?',
    options: { A: 'Jibreel and Mikail', B: 'Munkar and Nakir', C: 'Ridwan and Malik', D: 'Harut and Marut' },
    correct: 'B',
    explanation: 'Munkar and Nakir are the two angels who question the deceased in the grave about their faith.',
  },
  {
    id: 'gi-025',
    category: 'general',
    question: 'What is the name of the angel of death in Islam?',
    options: { A: 'Israfil', B: 'Jibreel', C: 'Malak al-Mawt', D: 'Mikail' },
    correct: 'C',
    explanation: 'The angel of death is known as Malak al-Mawt. Some traditions call him Azrael.',
  },
  {
    id: 'gi-026',
    category: 'general',
    question: 'What does "Ihsan" mean in Islamic belief?',
    options: { A: 'Fasting', B: 'Excellence — to worship Allah as if you see Him', C: 'Charity', D: 'Repentance' },
    correct: 'B',
    explanation: 'Ihsan means excellence in worship. The Prophet ﷺ defined it as "worshipping Allah as if you see Him, and if you cannot see Him, know that He sees you."',
  },
  {
    id: 'gi-027',
    category: 'general',
    question: 'What does "Tawbah" mean?',
    options: { A: 'Prayer', B: 'Fasting', C: 'Repentance', D: 'Patience' },
    correct: 'C',
    explanation: 'Tawbah means repentance — turning back to Allah with sincerity and asking for forgiveness.',
  },

  // === PRAYER / SALAH ===
  {
    id: 'gi-028',
    category: 'general',
    question: 'How many times do Muslims pray each day?',
    options: { A: '3', B: '4', C: '5', D: '7' },
    correct: 'C',
    explanation: 'Muslims perform five daily prayers: Fajr, Dhuhr, Asr, Maghrib, and Isha.',
  },
  {
    id: 'gi-029',
    category: 'general',
    question: 'How many rak\'ahs (units) are in the Fajr prayer?',
    options: { A: '3', B: '2', C: '4', D: '1' },
    correct: 'B',
    explanation: 'Fajr (dawn prayer) consists of 2 obligatory rak\'ahs.',
  },
  {
    id: 'gi-030',
    category: 'general',
    question: 'How many rak\'ahs are in the Maghrib prayer?',
    options: { A: '2', B: '4', C: '3', D: '5' },
    correct: 'C',
    explanation: 'Maghrib (sunset prayer) consists of 3 obligatory rak\'ahs.',
  },
  {
    id: 'gi-031',
    category: 'general',
    question: 'What is the call to prayer called?',
    options: { A: 'Iqamah', B: 'Adhan', C: 'Takbir', D: 'Tasbih' },
    correct: 'B',
    explanation: 'The Adhan is the call to prayer announced from the mosque to alert Muslims that it is time to pray.',
  },
  {
    id: 'gi-032',
    category: 'general',
    question: 'What surah must be recited in every rak\'ah of prayer?',
    options: { A: 'Al-Ikhlas', B: 'Al-Baqarah', C: 'Al-Fatihah', D: 'Al-Kawthar' },
    correct: 'C',
    explanation: 'Al-Fatihah (The Opening) is recited in every rak\'ah. The Prophet ﷺ said: "There is no prayer for one who does not recite Al-Fatihah."',
  },
  {
    id: 'gi-033',
    category: 'general',
    question: 'What is the ritual washing before prayer called?',
    options: { A: 'Ghusl', B: 'Tayammum', C: 'Wudu', D: 'Taharah' },
    correct: 'C',
    explanation: 'Wudu (ablution) is the ritual washing of the face, hands, head, and feet required before prayer.',
  },
  {
    id: 'gi-034',
    category: 'general',
    question: 'What is the dry ablution using sand or dust called?',
    options: { A: 'Wudu', B: 'Tayammum', C: 'Ghusl', D: 'Istinja' },
    correct: 'B',
    explanation: 'Tayammum is the dry ablution performed when water is unavailable or its use would cause harm.',
  },
  {
    id: 'gi-035',
    category: 'general',
    question: 'What is the bowing position in prayer called?',
    options: { A: 'Sujud', B: 'Ruku', C: 'Qiyam', D: 'Juloos' },
    correct: 'B',
    explanation: 'Ruku is the bowing position in prayer where the back is bent and hands rest on the knees.',
  },
  {
    id: 'gi-036',
    category: 'general',
    question: 'What is the prostration position in prayer called?',
    options: { A: 'Ruku', B: 'Qiyam', C: 'Sujud', D: 'Tashahhud' },
    correct: 'C',
    explanation: 'Sujud (prostration) is performed by placing the forehead, nose, both hands, both knees, and toes on the ground.',
  },
  {
    id: 'gi-037',
    category: 'general',
    question: 'How do Muslims end the prayer?',
    options: { A: 'By raising hands', B: 'By saying "Ameen"', C: 'By saying "Allahu Akbar"', D: 'By saying "Assalamu Alaykum" to the right and left' },
    correct: 'D',
    explanation: 'The prayer is concluded by making Tasleem — saying "Assalamu Alaykum wa Rahmatullah" to the right and then left.',
  },
  {
    id: 'gi-038',
    category: 'general',
    question: 'What is the special Friday prayer called?',
    options: { A: 'Tarawih', B: 'Jumu\'ah', C: 'Tahajjud', D: 'Duha' },
    correct: 'B',
    explanation: 'Jumu\'ah (Friday prayer) replaces Dhuhr on Fridays and includes a khutbah (sermon).',
  },
  {
    id: 'gi-039',
    category: 'general',
    question: 'What is the voluntary night prayer during Ramadan called?',
    options: { A: 'Tahajjud', B: 'Witr', C: 'Tarawih', D: 'Duha' },
    correct: 'C',
    explanation: 'Tarawih is the special voluntary night prayer performed during Ramadan after Isha.',
  },
  {
    id: 'gi-040',
    category: 'general',
    question: 'What phrase begins the prayer?',
    options: { A: 'Bismillah', B: 'Subhanallah', C: 'Alhamdulillah', D: 'Allahu Akbar' },
    correct: 'D',
    explanation: 'The prayer begins with the Takbiratul Ihram — saying "Allahu Akbar" (Allah is the Greatest) while raising both hands.',
  },
  {
    id: 'gi-041',
    category: 'general',
    question: 'What does "Allahu Akbar" mean?',
    options: { A: 'Allah is One', B: 'Praise be to Allah', C: 'Allah is the Greatest', D: 'There is no god but Allah' },
    correct: 'C',
    explanation: '"Allahu Akbar" means "Allah is the Greatest." It is said during prayer and in many daily situations.',
  },
  {
    id: 'gi-042',
    category: 'general',
    question: 'What is the direction Muslims face when praying?',
    options: { A: 'East', B: 'West', C: 'The Qiblah (toward the Ka\'bah in Mecca)', D: 'Jerusalem' },
    correct: 'C',
    explanation: 'Muslims face the Qiblah — the direction of the Ka\'bah in Mecca — during prayer.',
  },
  {
    id: 'gi-043',
    category: 'general',
    question: 'How many rak\'ahs are in the Dhuhr prayer?',
    options: { A: '4', B: '2', C: '3', D: '5' },
    correct: 'A',
    explanation: 'Dhuhr (midday prayer) consists of 4 obligatory rak\'ahs.',
  },
  {
    id: 'gi-044',
    category: 'general',
    question: 'What is the late-night voluntary prayer called?',
    options: { A: 'Tarawih', B: 'Tahajjud', C: 'Duha', D: 'Witr' },
    correct: 'B',
    explanation: 'Tahajjud is a voluntary night prayer performed in the last third of the night. Allah praises those who perform it.',
  },
  {
    id: 'gi-045',
    category: 'general',
    question: 'What is "Khushu" in prayer?',
    options: { A: 'The number of rak\'ahs', B: 'Humility and focus in prayer', C: 'The call to prayer', D: 'A type of prostration' },
    correct: 'B',
    explanation: 'Khushu means humility, attentiveness, and focus during prayer — being fully present before Allah.',
  },
  {
    id: 'gi-046',
    category: 'general',
    question: 'What prayer mat do Muslims use?',
    options: { A: 'Sajjadah', B: 'Musalla', C: 'Both A and B are correct terms', D: 'Qiblah' },
    correct: 'C',
    explanation: 'Both "sajjadah" and "musalla" refer to the prayer mat used by Muslims for prayer.',
  },
  {
    id: 'gi-047',
    category: 'general',
    question: 'What is the pulpit in a mosque called?',
    options: { A: 'Mihrab', B: 'Minaret', C: 'Minbar', D: 'Musalla' },
    correct: 'C',
    explanation: 'The Minbar is the raised platform or pulpit in a mosque from which the imam delivers the khutbah (sermon).',
  },

  // === THE QURAN ===
  {
    id: 'gi-048',
    category: 'general',
    question: 'How many chapters (surahs) are in the Quran?',
    options: { A: '99', B: '114', C: '120', D: '100' },
    correct: 'B',
    explanation: 'The Quran contains 114 surahs (chapters), ranging in length from 3 to 286 verses.',
  },
  {
    id: 'gi-049',
    category: 'general',
    question: 'How many parts (juz) is the Quran divided into?',
    options: { A: '20', B: '25', C: '30', D: '114' },
    correct: 'C',
    explanation: 'The Quran is divided into 30 equal parts called juz (or para), used to help complete the Quran in a month.',
  },
  {
    id: 'gi-050',
    category: 'general',
    question: 'What is the first surah of the Quran?',
    options: { A: 'Al-Baqarah', B: 'Al-Fatihah', C: 'Al-Ikhlas', D: 'Ya-Sin' },
    correct: 'B',
    explanation: 'Al-Fatihah (The Opening) is the first surah of the Quran and is recited in every unit of prayer.',
  },
  {
    id: 'gi-051',
    category: 'general',
    question: 'Which is the longest surah in the Quran?',
    options: { A: 'Al-Imran', B: 'An-Nisa', C: 'Al-Baqarah', D: 'Al-Maidah' },
    correct: 'C',
    explanation: 'Al-Baqarah is the longest surah with 286 verses. It is the second chapter of the Quran.',
  },
  {
    id: 'gi-052',
    category: 'general',
    question: 'Which is the shortest surah in the Quran?',
    options: { A: 'Al-Fatihah', B: 'Al-Ikhlas', C: 'Al-Kawthar', D: 'Al-Asr' },
    correct: 'C',
    explanation: 'Al-Kawthar has only 3 verses, making it the shortest surah in the Quran.',
  },
  {
    id: 'gi-053',
    category: 'general',
    question: 'What were the first words revealed of the Quran?',
    options: { A: 'Bismillah', B: 'Alhamdulillah', C: 'Iqra (Read)', D: 'La ilaha illallah' },
    correct: 'C',
    explanation: 'The first word revealed was "Iqra" (Read/Recite) from Surah Al-Alaq, revealed to the Prophet ﷺ in the Cave of Hira.',
  },
  {
    id: 'gi-054',
    category: 'general',
    question: 'Which surah is known as "the heart of the Quran"?',
    options: { A: 'Al-Fatihah', B: 'Al-Baqarah', C: 'Al-Ikhlas', D: 'Ya-Sin' },
    correct: 'D',
    explanation: 'Ya-Sin is called the heart of the Quran. The Prophet ﷺ said: "Everything has a heart, and the heart of the Quran is Ya-Sin."',
  },
  {
    id: 'gi-055',
    category: 'general',
    question: 'Which surah is described as being equal to one-third of the Quran?',
    options: { A: 'Al-Fatihah', B: 'Al-Ikhlas', C: 'Al-Falaq', D: 'Al-Kawthar' },
    correct: 'B',
    explanation: 'Al-Ikhlas is described as equal to one-third of the Quran because it describes the perfect oneness (Tawhid) of Allah.',
  },
  {
    id: 'gi-056',
    category: 'general',
    question: 'What is the verse of the Throne called?',
    options: { A: 'Ayat al-Nur', B: 'Ayat al-Kursi', C: 'Ayat al-Sajdah', D: 'Ayat al-Mawaddah' },
    correct: 'B',
    explanation: 'Ayat al-Kursi is verse 255 of Surah Al-Baqarah. The Prophet ﷺ called it the greatest verse in the Quran.',
  },
  {
    id: 'gi-057',
    category: 'general',
    question: 'What does "Quran" mean in Arabic?',
    options: { A: 'The Final Word', B: 'The Divine Message', C: 'That which is recited', D: 'The Light' },
    correct: 'C',
    explanation: 'The word "Quran" comes from the root word "qara\'a" meaning to read or recite.',
  },
  {
    id: 'gi-058',
    category: 'general',
    question: 'In which month was the Quran first revealed?',
    options: { A: 'Muharram', B: 'Sha\'ban', C: 'Dhul-Hijjah', D: 'Ramadan' },
    correct: 'D',
    explanation: 'The Quran began to be revealed in the month of Ramadan. Allah says: "The month of Ramadan in which was revealed the Quran." (2:185)',
  },
  {
    id: 'gi-059',
    category: 'general',
    question: 'What is the study of the rules of Quranic recitation called?',
    options: { A: 'Fiqh', B: 'Tajweed', C: 'Tafsir', D: 'Hadith' },
    correct: 'B',
    explanation: 'Tajweed is the set of rules governing the correct pronunciation and recitation of the Quran.',
  },
  {
    id: 'gi-060',
    category: 'general',
    question: 'What is the interpretation and explanation of the Quran called?',
    options: { A: 'Tajweed', B: 'Hadith', C: 'Tafsir', D: 'Fiqh' },
    correct: 'C',
    explanation: 'Tafsir is the scholarly explanation and interpretation of the meaning of the Quran.',
  },
  {
    id: 'gi-061',
    category: 'general',
    question: 'What are the protective surahs (Al-Mu\'awwidhatayn)?',
    options: { A: 'Al-Falaq and An-Nas', B: 'Al-Ikhlas and Al-Fatihah', C: 'Ya-Sin and Al-Mulk', D: 'Al-Kawthar and Al-Asr' },
    correct: 'A',
    explanation: 'Al-Falaq and An-Nas are known as Al-Mu\'awwidhatayn (the two surahs of seeking refuge). They are recited for protection.',
  },
  {
    id: 'gi-062',
    category: 'general',
    question: 'What is a person who has memorised the entire Quran called?',
    options: { A: 'Mufti', B: 'Imam', C: 'Hafiz', D: 'Qari' },
    correct: 'C',
    explanation: 'A Hafiz is someone who has memorised the entire Quran by heart. The word means "one who preserves."',
  },
  {
    id: 'gi-063',
    category: 'general',
    question: 'What phrase do Muslims say before beginning any action?',
    options: { A: 'Alhamdulillah', B: 'Bismillah', C: 'Subhanallah', D: 'Allahu Akbar' },
    correct: 'B',
    explanation: '"Bismillah" (In the name of Allah) is said before beginning any action, following the Sunnah of the Prophet ﷺ.',
  },

  // === PROPHET MUHAMMAD ﷺ BASICS ===
  {
    id: 'gi-064',
    category: 'general',
    question: 'Where was Prophet Muhammad ﷺ born?',
    options: { A: 'Madinah', B: 'Jerusalem', C: 'Mecca', D: 'Ta\'if' },
    correct: 'C',
    explanation: 'Prophet Muhammad ﷺ was born in Mecca in approximately 570 CE, in the year known as the Year of the Elephant.',
  },
  {
    id: 'gi-065',
    category: 'general',
    question: 'What was Prophet Muhammad\'s ﷺ father\'s name?',
    options: { A: 'Abu Talib', B: 'Abdullah', C: 'Abdul Muttalib', D: 'Abu Bakr' },
    correct: 'B',
    explanation: 'The Prophet\'s ﷺ father was Abdullah ibn Abdul Muttalib, who passed away before the Prophet\'s birth.',
  },
  {
    id: 'gi-066',
    category: 'general',
    question: 'What was Prophet Muhammad\'s ﷺ mother\'s name?',
    options: { A: 'Khadijah', B: 'Fatimah', C: 'Aminah', D: 'Maryam' },
    correct: 'C',
    explanation: 'The Prophet\'s ﷺ mother was Aminah bint Wahb. She passed away when the Prophet was around six years old.',
  },
  {
    id: 'gi-067',
    category: 'general',
    question: 'Who was the Prophet\'s ﷺ first wife?',
    options: { A: 'Aisha', B: 'Khadijah', C: 'Hafsa', D: 'Zaynab' },
    correct: 'B',
    explanation: 'Khadijah bint Khuwaylid was the Prophet\'s ﷺ first wife and the first person to accept Islam. They were married for 25 years.',
  },
  {
    id: 'gi-068',
    category: 'general',
    question: 'In which cave did the Prophet ﷺ receive his first revelation?',
    options: { A: 'Cave of Thawr', B: 'Cave of Hira', C: 'Cave of Uhud', D: 'Cave of Badr' },
    correct: 'B',
    explanation: 'The first revelation came to the Prophet ﷺ in the Cave of Hira on Jabal al-Nour (Mountain of Light) near Mecca.',
  },
  {
    id: 'gi-069',
    category: 'general',
    question: 'What is the Prophet\'s ﷺ migration from Mecca to Madinah called?',
    options: { A: 'Isra', B: 'Hijra', C: 'Mi\'raj', D: 'Ghazwah' },
    correct: 'B',
    explanation: 'The Hijra (migration) in 622 CE marks the beginning of the Islamic calendar. The Prophet ﷺ migrated to Madinah to escape persecution.',
  },
  {
    id: 'gi-070',
    category: 'general',
    question: 'What nickname was the Prophet ﷺ known by for his honesty?',
    options: { A: 'Al-Ghani', B: 'Al-Karim', C: 'Al-Amin', D: 'Al-Hadi' },
    correct: 'C',
    explanation: 'The Prophet ﷺ was called "Al-Amin" (The Trustworthy) by the people of Mecca even before prophethood, due to his honesty.',
  },
  {
    id: 'gi-071',
    category: 'general',
    question: 'What tribe did Prophet Muhammad ﷺ belong to?',
    options: { A: 'Aws', B: 'Khazraj', C: 'Thaqif', D: 'Quraysh' },
    correct: 'D',
    explanation: 'The Prophet ﷺ belonged to the Quraysh tribe, specifically the Banu Hashim clan.',
  },
  {
    id: 'gi-072',
    category: 'general',
    question: 'Who was the first person to accept Islam?',
    options: { A: 'Abu Bakr', B: 'Ali ibn Abi Talib', C: 'Khadijah', D: 'Umar ibn al-Khattab' },
    correct: 'C',
    explanation: 'Khadijah, the Prophet\'s ﷺ wife, was the first person to accept Islam. Among men, Ali ibn Abi Talib was among the first.',
  },
  {
    id: 'gi-073',
    category: 'general',
    question: 'What is the Prophet\'s ﷺ miraculous night journey to Jerusalem and ascension to the heavens called?',
    options: { A: 'Hijra', B: 'Isra and Mi\'raj', C: 'Laylatul Qadr', D: 'Ghazwah' },
    correct: 'B',
    explanation: 'Isra is the night journey to Jerusalem; Mi\'raj is the ascension to the heavens. Both occurred in a single night.',
  },
  {
    id: 'gi-074',
    category: 'general',
    question: 'Who was the first Caliph after the Prophet Muhammad ﷺ?',
    options: { A: 'Umar ibn al-Khattab', B: 'Uthman ibn Affan', C: 'Ali ibn Abi Talib', D: 'Abu Bakr al-Siddiq' },
    correct: 'D',
    explanation: 'Abu Bakr al-Siddiq was the first Caliph. He was the closest companion of the Prophet ﷺ and his father-in-law.',
  },
  {
    id: 'gi-075',
    category: 'general',
    question: 'What is the collection of the Prophet\'s ﷺ sayings and actions called?',
    options: { A: 'Tafsir', B: 'Fiqh', C: 'Seerah', D: 'Hadith' },
    correct: 'D',
    explanation: 'Hadith are the recorded sayings, actions, and approvals of Prophet Muhammad ﷺ. They are a primary source of Islamic guidance.',
  },
  {
    id: 'gi-076',
    category: 'general',
    question: 'What is the biography of Prophet Muhammad ﷺ called?',
    options: { A: 'Tafsir', B: 'Seerah', C: 'Hadith', D: 'Fiqh' },
    correct: 'B',
    explanation: 'Seerah refers to the biography and life story of Prophet Muhammad ﷺ.',
  },
  {
    id: 'gi-077',
    category: 'general',
    question: 'In which year did the Prophet ﷺ pass away?',
    options: { A: '622 CE', B: '610 CE', C: '632 CE', D: '640 CE' },
    correct: 'C',
    explanation: 'Prophet Muhammad ﷺ passed away in 632 CE (11 AH) in Madinah at approximately 63 years of age.',
  },
  {
    id: 'gi-078',
    category: 'general',
    question: 'What is the model way of the Prophet ﷺ that Muslims are encouraged to follow?',
    options: { A: 'Fiqh', B: 'Sunnah', C: 'Ijma', D: 'Qiyas' },
    correct: 'B',
    explanation: 'The Sunnah refers to the Prophet\'s ﷺ practices, habits, and way of life that Muslims are encouraged to emulate.',
  },

  // === ISLAMIC CALENDAR & MONTHS ===
  {
    id: 'gi-079',
    category: 'general',
    question: 'How many months are in the Islamic (Hijri) calendar?',
    options: { A: '10', B: '11', C: '13', D: '12' },
    correct: 'D',
    explanation: 'The Islamic Hijri calendar has 12 lunar months. Each month begins with the sighting of the new crescent moon.',
  },
  {
    id: 'gi-080',
    category: 'general',
    question: 'What is the first month of the Islamic calendar?',
    options: { A: 'Ramadan', B: 'Muharram', C: 'Dhul-Hijjah', D: 'Rajab' },
    correct: 'B',
    explanation: 'Muharram is the first month of the Islamic Hijri calendar and is one of the four sacred months.',
  },
  {
    id: 'gi-081',
    category: 'general',
    question: 'Which Islamic month is the most sacred?',
    options: { A: 'Sha\'ban', B: 'Rajab', C: 'Muharram', D: 'Ramadan' },
    correct: 'D',
    explanation: 'Ramadan is the most sacred month as it is when the Quran was revealed, and fasting in it is obligatory.',
  },
  {
    id: 'gi-082',
    category: 'general',
    question: 'On which day is Eid al-Fitr celebrated?',
    options: { A: '1st Muharram', B: '10th Dhul-Hijjah', C: '1st Shawwal', D: '27th Ramadan' },
    correct: 'C',
    explanation: 'Eid al-Fitr is celebrated on the 1st of Shawwal, marking the end of Ramadan.',
  },
  {
    id: 'gi-083',
    category: 'general',
    question: 'On which day is Eid al-Adha celebrated?',
    options: { A: '1st Shawwal', B: '10th Dhul-Hijjah', C: '1st Muharram', D: '10th Muharram' },
    correct: 'B',
    explanation: 'Eid al-Adha is celebrated on the 10th of Dhul-Hijjah, coinciding with the Hajj pilgrimage.',
  },
  {
    id: 'gi-084',
    category: 'general',
    question: 'What is the day of Ashura?',
    options: { A: '1st Muharram', B: '10th Muharram', C: '10th Ramadan', D: '27th Rajab' },
    correct: 'B',
    explanation: 'Ashura is the 10th of Muharram. The Prophet ﷺ fasted on this day and recommended fasting it.',
  },
  {
    id: 'gi-085',
    category: 'general',
    question: 'Which are the four sacred months in Islam?',
    options: {
      A: 'Muharram, Rajab, Sha\'ban, Ramadan',
      B: 'Muharram, Rajab, Dhul-Qa\'dah, Dhul-Hijjah',
      C: 'Ramadan, Shawwal, Dhul-Qa\'dah, Dhul-Hijjah',
      D: 'Rajab, Sha\'ban, Ramadan, Shawwal',
    },
    correct: 'B',
    explanation: 'The four sacred (Haram) months are Muharram, Rajab, Dhul-Qa\'dah, and Dhul-Hijjah. Fighting is prohibited in these months.',
  },
  {
    id: 'gi-086',
    category: 'general',
    question: 'What is the last month of the Islamic calendar?',
    options: { A: 'Shawwal', B: 'Ramadan', C: 'Dhul-Hijjah', D: 'Muharram' },
    correct: 'C',
    explanation: 'Dhul-Hijjah is the 12th and final month of the Islamic calendar. Hajj and Eid al-Adha occur in this month.',
  },
  {
    id: 'gi-087',
    category: 'general',
    question: 'What significant event marks the start of the Islamic calendar (year 1 AH)?',
    options: { A: 'The first revelation', B: 'The birth of the Prophet ﷺ', C: 'The Hijra to Madinah', D: 'The conquest of Mecca' },
    correct: 'C',
    explanation: 'The Islamic calendar begins from the year of the Hijra (migration) of the Prophet ﷺ from Mecca to Madinah (622 CE).',
  },
  {
    id: 'gi-088',
    category: 'general',
    question: 'What is the Night of Power called and in which month does it occur?',
    options: { A: 'Laylatul Qadr — in Ramadan', B: 'Laylatul Barat — in Sha\'ban', C: 'Laylatul Isra — in Rajab', D: 'Laylatul Eid — in Shawwal' },
    correct: 'A',
    explanation: 'Laylatul Qadr (Night of Power) occurs in the last 10 nights of Ramadan, most likely on one of the odd nights.',
  },

  // === ISLAMIC ETIQUETTE & DAILY PRACTICES ===
  {
    id: 'gi-089',
    category: 'general',
    question: 'What is the Islamic greeting?',
    options: { A: 'Bismillah', B: 'Alhamdulillah', C: 'As-Salamu Alaykum', D: 'Allahu Akbar' },
    correct: 'C',
    explanation: '"As-Salamu Alaykum" (Peace be upon you) is the Islamic greeting. The response is "Wa Alaykum As-Salam."',
  },
  {
    id: 'gi-090',
    category: 'general',
    question: 'What do Muslims say when something good happens?',
    options: { A: 'Subhanallah', B: 'Alhamdulillah', C: 'Inshallah', D: 'Mashallah' },
    correct: 'B',
    explanation: '"Alhamdulillah" (All praise is for Allah) is said when something good happens to thank Allah.',
  },
  {
    id: 'gi-091',
    category: 'general',
    question: 'What do Muslims say when they are amazed or see something beautiful?',
    options: { A: 'Alhamdulillah', B: 'Subhanallah', C: 'Inshallah', D: 'Mashallah' },
    correct: 'D',
    explanation: '"Mashallah" (What Allah has willed) is said to express admiration and acknowledge that blessings come from Allah.',
  },
  {
    id: 'gi-092',
    category: 'general',
    question: 'What do Muslims say when planning to do something in the future?',
    options: { A: 'Alhamdulillah', B: 'Mashallah', C: 'Inshallah', D: 'Subhanallah' },
    correct: 'C',
    explanation: '"Inshallah" (If Allah wills) is said when speaking about future plans, acknowledging that everything depends on Allah\'s will.',
  },
  {
    id: 'gi-093',
    category: 'general',
    question: 'What do Muslims say when they hear of someone\'s death?',
    options: { A: 'Alhamdulillah', B: 'Inna lillahi wa inna ilayhi raji\'un', C: 'Subhanallah', D: 'Bismillah' },
    correct: 'B',
    explanation: '"Inna lillahi wa inna ilayhi raji\'un" (Indeed, to Allah we belong and to Him we return) is said upon hearing of a death.',
  },
  {
    id: 'gi-094',
    category: 'general',
    question: 'What is "Salawat" (Durood)?',
    options: { A: 'A type of prayer', B: 'Sending blessings upon the Prophet ﷺ', C: 'A charity', D: 'A form of fasting' },
    correct: 'B',
    explanation: 'Salawat (Durood) is the act of sending blessings and peace upon Prophet Muhammad ﷺ, as Allah commands in the Quran (33:56).',
  },
  {
    id: 'gi-095',
    category: 'general',
    question: 'What does "Subhanallah" mean?',
    options: { A: 'Allah is the Greatest', B: 'Praise be to Allah', C: 'Glory be to Allah', D: 'There is no god but Allah' },
    correct: 'C',
    explanation: '"Subhanallah" means "Glory be to Allah" or "Allah is free from imperfection." It expresses amazement and reverence.',
  },
  {
    id: 'gi-096',
    category: 'general',
    question: 'What is the supplication (du\'a) said before eating?',
    options: { A: 'Alhamdulillah', B: 'Bismillah', C: 'Subhanallah', D: 'Inshallah' },
    correct: 'B',
    explanation: 'The Sunnah is to say "Bismillah" before eating. If one forgets, they say "Bismillahi awwalahu wa akhirah."',
  },
  {
    id: 'gi-097',
    category: 'general',
    question: 'Which hand should Muslims use when eating and drinking?',
    options: { A: 'Left hand', B: 'Right hand', C: 'Either hand', D: 'Both hands together' },
    correct: 'B',
    explanation: 'Muslims use the right hand for eating and drinking, as the Prophet ﷺ instructed: "Eat with your right hand."',
  },
  {
    id: 'gi-098',
    category: 'general',
    question: 'What is the Arabic term for prohibited actions in Islam?',
    options: { A: 'Halal', B: 'Makruh', C: 'Haram', D: 'Mustahabb' },
    correct: 'C',
    explanation: 'Haram refers to actions that are explicitly forbidden in Islam, such as consuming alcohol or pork.',
  },
  {
    id: 'gi-099',
    category: 'general',
    question: 'What does "Halal" mean?',
    options: { A: 'Forbidden', B: 'Permissible/Lawful', C: 'Obligatory', D: 'Disliked' },
    correct: 'B',
    explanation: 'Halal means permissible or lawful. It refers to anything allowed under Islamic law.',
  },
  {
    id: 'gi-100',
    category: 'general',
    question: 'What is the Islamic concept of modesty and covering called?',
    options: { A: 'Taqwa', B: 'Hayaa', C: 'Hijab', D: 'Iman' },
    correct: 'C',
    explanation: 'Hijab refers to the concept of modesty and covering in Islam. For women, it typically refers to the headscarf.',
  },

  // === BASIC ISLAMIC TERMS ===
  {
    id: 'gi-101',
    category: 'general',
    question: 'What does "Allah" mean?',
    options: { A: 'The Most Merciful', B: 'The Creator', C: 'The One True God', D: 'The King' },
    correct: 'C',
    explanation: '"Allah" is the Arabic word for the One True God. It has no plural and no gender, making it unique as a name for God.',
  },
  {
    id: 'gi-102',
    category: 'general',
    question: 'What is "Tawhid"?',
    options: { A: 'Islamic prayer', B: 'The oneness of Allah', C: 'The Quran', D: 'Fasting' },
    correct: 'B',
    explanation: 'Tawhid is the fundamental Islamic concept of the absolute oneness and uniqueness of Allah.',
  },
  {
    id: 'gi-103',
    category: 'general',
    question: 'What is a "Masjid"?',
    options: { A: 'Islamic school', B: 'Mosque (place of worship)', C: 'Islamic court', D: 'Religious leader' },
    correct: 'B',
    explanation: 'Masjid (mosque) is the place of worship for Muslims. The word means "place of prostration."',
  },
  {
    id: 'gi-104',
    category: 'general',
    question: 'What is an "Imam"?',
    options: { A: 'A type of prayer', B: 'A Muslim scholar or leader of prayer', C: 'A chapter of the Quran', D: 'A form of charity' },
    correct: 'B',
    explanation: 'An Imam is a Muslim leader or the person who leads congregational prayer.',
  },
  {
    id: 'gi-105',
    category: 'general',
    question: 'What does "Alhamdulillah" mean?',
    options: { A: 'Allah is the Greatest', B: 'In the name of Allah', C: 'All praise and thanks be to Allah', D: 'Glory be to Allah' },
    correct: 'C',
    explanation: '"Alhamdulillah" means "All praise and thanks be to Allah." It is said in gratitude and after good events.',
  },
  {
    id: 'gi-106',
    category: 'general',
    question: 'What is "Sadaqah"?',
    options: { A: 'Obligatory prayer', B: 'Voluntary charity', C: 'Obligatory fasting', D: 'Islamic law' },
    correct: 'B',
    explanation: 'Sadaqah is voluntary charity given freely for the sake of Allah. Unlike Zakat, it has no fixed amount.',
  },
  {
    id: 'gi-107',
    category: 'general',
    question: 'What is "Taqwa"?',
    options: { A: 'Fasting', B: 'Charity', C: 'Consciousness and fear of Allah / God-consciousness', D: 'Prayer' },
    correct: 'C',
    explanation: 'Taqwa is the consciousness, awareness, and fear of Allah that leads a person to avoid sin and do good.',
  },
  {
    id: 'gi-108',
    category: 'general',
    question: 'What does "Salam" mean?',
    options: { A: 'Prayer', B: 'Peace', C: 'Blessing', D: 'Submission' },
    correct: 'B',
    explanation: '"Salam" means peace. "As-Salamu Alaykum" means "Peace be upon you."',
  },
  {
    id: 'gi-109',
    category: 'general',
    question: 'What is "Shirk" in Islam?',
    options: { A: 'Charity', B: 'Fasting', C: 'Associating partners with Allah', D: 'Prayer' },
    correct: 'C',
    explanation: 'Shirk is the act of associating partners with Allah. It is considered the greatest sin in Islam.',
  },
  {
    id: 'gi-110',
    category: 'general',
    question: 'What is a "Fatwa"?',
    options: { A: 'A type of prayer', B: 'A religious ruling or legal opinion', C: 'A chapter of the Quran', D: 'A form of fasting' },
    correct: 'B',
    explanation: 'A Fatwa is a formal religious ruling or opinion given by a qualified Islamic scholar (mufti) on a matter.',
  },

  // === HAJJ DETAILS ===
  {
    id: 'gi-111',
    category: 'general',
    question: 'What is the seamless white garment worn by male pilgrims during Hajj called?',
    options: { A: 'Thobe', B: 'Bisht', C: 'Ihram', D: 'Izar' },
    correct: 'C',
    explanation: 'Ihram refers to both the sacred state of pilgrimage and the two-piece white unsewn cloth worn by male pilgrims.',
  },
  {
    id: 'gi-112',
    category: 'general',
    question: 'What is the plain near Mecca where pilgrims stand in prayer during Hajj?',
    options: { A: 'Mina', B: 'Muzdalifah', C: 'Arafah', D: 'Jamarat' },
    correct: 'C',
    explanation: 'Standing at the plain of Arafah on the 9th of Dhul-Hijjah is the most essential part of Hajj. The Prophet ﷺ said: "Hajj is Arafah."',
  },
  {
    id: 'gi-113',
    category: 'general',
    question: 'What do pilgrims do at Jamarat during Hajj?',
    options: { A: 'Pray Fajr', B: 'Perform Tawaf', C: 'Throw pebbles (stoning the devil)', D: 'Sacrifice an animal' },
    correct: 'C',
    explanation: 'Pilgrims throw pebbles at three pillars (jamarat) in Mina, commemorating Ibrahim\'s rejection of Shaytan.',
  },
  {
    id: 'gi-114',
    category: 'general',
    question: 'What spring of water near the Ka\'bah do pilgrims drink?',
    options: { A: 'Safa water', B: 'Nile water', C: 'Zamzam water', D: 'Arafah water' },
    correct: 'C',
    explanation: 'Zamzam is the blessed water that miraculously sprang up for Hajar and baby Ismail. Pilgrims drink it during Hajj and Umrah.',
  },
  {
    id: 'gi-115',
    category: 'general',
    question: 'Who built the Ka\'bah?',
    options: { A: 'Prophet Adam and his sons', B: 'Prophet Ibrahim and his son Ismail', C: 'Prophet Musa and Harun', D: 'Prophet Muhammad ﷺ' },
    correct: 'B',
    explanation: 'Prophet Ibrahim (Abraham) and his son Ismail (Ishmael) built the Ka\'bah as a house of worship for Allah.',
  },
  {
    id: 'gi-116',
    category: 'general',
    question: 'What is the smaller pilgrimage that can be done any time of year called?',
    options: { A: 'Hajj', B: 'Umrah', C: 'Tawaf', D: 'I\'tikaf' },
    correct: 'B',
    explanation: 'Umrah is the lesser pilgrimage that can be performed at any time of year. It includes Tawaf and Sa\'i but is not obligatory.',
  },
  {
    id: 'gi-117',
    category: 'general',
    question: 'What is the black stone set in the corner of the Ka\'bah called?',
    options: { A: 'Al-Hajar al-Abyad', B: 'Al-Hajar al-Aswad', C: 'Zamzam Stone', D: 'Maqam Ibrahim' },
    correct: 'B',
    explanation: 'Al-Hajar al-Aswad (the Black Stone) is set in the eastern corner of the Ka\'bah. Pilgrims begin Tawaf from it.',
  },

  // === PARADISE AND AFTERLIFE ===
  {
    id: 'gi-118',
    category: 'general',
    question: 'What is the Islamic term for Paradise?',
    options: { A: 'Jahannam', B: 'Jannah', C: 'Sirat', D: 'Mizan' },
    correct: 'B',
    explanation: 'Jannah (Paradise/Garden) is the eternal reward for the believers in the afterlife.',
  },
  {
    id: 'gi-119',
    category: 'general',
    question: 'What is the Islamic term for Hell?',
    options: { A: 'Jannah', B: 'Barzakh', C: 'Jahannam', D: 'Mizan' },
    correct: 'C',
    explanation: 'Jahannam is the Islamic term for Hell — the place of punishment for those who rejected Allah and did evil.',
  },
  {
    id: 'gi-120',
    category: 'general',
    question: 'What is the bridge over Hellfire that everyone must cross on the Day of Judgment called?',
    options: { A: 'Mizan', B: 'Sirat', C: 'Barzakh', D: 'Hawd' },
    correct: 'B',
    explanation: 'The Sirat is the bridge over Hellfire. Believers cross it at different speeds according to their deeds.',
  },
  {
    id: 'gi-121',
    category: 'general',
    question: 'What is "Barzakh"?',
    options: { A: 'A name for Paradise', B: 'The barrier / realm between death and the Day of Judgment', C: 'A form of charity', D: 'A type of prayer' },
    correct: 'B',
    explanation: 'Barzakh is the realm or barrier between death and the Day of Judgment — the intermediate state of the soul.',
  },

  // === NAMES & ATTRIBUTES OF ALLAH ===
  {
    id: 'gi-122',
    category: 'general',
    question: 'How many Beautiful Names of Allah (Asma\' al-Husna) are mentioned in a famous hadith?',
    options: { A: '33', B: '66', C: '99', D: '100' },
    correct: 'C',
    explanation: 'The Prophet ﷺ said: "Allah has 99 names. Whoever memorises them will enter Paradise." (Bukhari)',
  },
  {
    id: 'gi-123',
    category: 'general',
    question: 'What does "Al-Rahman" mean?',
    options: { A: 'The All-Knowing', B: 'The Most Merciful', C: 'The King', D: 'The Provider' },
    correct: 'B',
    explanation: 'Al-Rahman means "The Most Merciful" — a general mercy that encompasses all of creation.',
  },
  {
    id: 'gi-124',
    category: 'general',
    question: 'What does "Al-Rahim" mean?',
    options: { A: 'The Wise', B: 'The Creator', C: 'The Especially Merciful (to believers)', D: 'The Provider' },
    correct: 'C',
    explanation: 'Al-Rahim means "The Especially Merciful" — a specific mercy reserved especially for the believers.',
  },
  {
    id: 'gi-125',
    category: 'general',
    question: 'What does "Al-Khaliq" mean?',
    options: { A: 'The Provider', B: 'The All-Knowing', C: 'The Creator', D: 'The Eternal' },
    correct: 'C',
    explanation: 'Al-Khaliq means "The Creator." Allah alone has the power to create from nothing.',
  },
  {
    id: 'gi-126',
    category: 'general',
    question: 'What does "Al-Alim" mean?',
    options: { A: 'The All-Hearing', B: 'The All-Seeing', C: 'The All-Knowing', D: 'The All-Aware' },
    correct: 'C',
    explanation: 'Al-Alim means "The All-Knowing." Allah has complete and perfect knowledge of everything.',
  },
  {
    id: 'gi-127',
    category: 'general',
    question: 'What does "Al-Ghafur" mean?',
    options: { A: 'The Most Generous', B: 'The Most Forgiving', C: 'The Most Powerful', D: 'The Most Patient' },
    correct: 'B',
    explanation: 'Al-Ghafur means "The Most Forgiving." Allah forgives the sins of whoever sincerely repents.',
  },
  {
    id: 'gi-128',
    category: 'general',
    question: 'What does "Al-Razzaq" mean?',
    options: { A: 'The Creator', B: 'The Sustainer and Provider', C: 'The Just', D: 'The Mighty' },
    correct: 'B',
    explanation: 'Al-Razzaq means "The Sustainer and Provider." Allah provides sustenance for all creation.',
  },

  // === PROPHETS (GENERAL) ===
  {
    id: 'gi-129',
    category: 'general',
    question: 'How many prophets are mentioned by name in the Quran?',
    options: { A: '10', B: '25', C: '30', D: '50' },
    correct: 'B',
    explanation: '25 prophets are mentioned by name in the Quran, from Adam to Muhammad ﷺ.',
  },
  {
    id: 'gi-130',
    category: 'general',
    question: 'Who was the first prophet?',
    options: { A: 'Ibrahim', B: 'Nuh', C: 'Adam', D: 'Idris' },
    correct: 'C',
    explanation: 'Adam (peace be upon him) was the first human being and the first prophet. He was created by Allah from clay.',
  },
  {
    id: 'gi-131',
    category: 'general',
    question: 'Who was the last and final prophet?',
    options: { A: 'Isa (Jesus)', B: 'Ibrahim (Abraham)', C: 'Muhammad ﷺ', D: 'Musa (Moses)' },
    correct: 'C',
    explanation: 'Muhammad ﷺ is the last and final prophet (Khatam al-Nabiyyin). No prophet will come after him.',
  },
  {
    id: 'gi-132',
    category: 'general',
    question: 'What is the Arabic title for a prophet who also brought a new scripture or law?',
    options: { A: 'Nabi', B: 'Rasul', C: 'Imam', D: 'Wali' },
    correct: 'B',
    explanation: 'A Rasul (messenger) is a prophet who brought a new scripture or law. A Nabi is a prophet who continued a previous law.',
  },
  {
    id: 'gi-133',
    category: 'general',
    question: 'Which prophet is known as "Khalilullah" (Friend of Allah)?',
    options: { A: 'Musa', B: 'Dawud', C: 'Ibrahim', D: 'Isa' },
    correct: 'C',
    explanation: 'Ibrahim (Abraham) is known as Khalilullah — the intimate friend of Allah.',
  },
  {
    id: 'gi-134',
    category: 'general',
    question: 'Which prophet is known as "Kalimullah" (He who spoke directly to Allah)?',
    options: { A: 'Ibrahim', B: 'Musa', C: 'Isa', D: 'Yunus' },
    correct: 'B',
    explanation: 'Musa (Moses) is known as Kalimullah because Allah spoke to him directly without an intermediary.',
  },
  {
    id: 'gi-135',
    category: 'general',
    question: 'Which prophet is known as "Ruhullah" (Spirit of Allah)?',
    options: { A: 'Yahya', B: 'Ibrahim', C: 'Isa', D: 'Musa' },
    correct: 'C',
    explanation: 'Isa (Jesus) is referred to as "Ruhullah" (Spirit from Allah) in the Quran. He was created without a father by Allah\'s command.',
  },

  // === RAMADAN SPECIAL ===
  {
    id: 'gi-136',
    category: 'general',
    question: 'What is "I\'tikaf"?',
    options: { A: 'Voluntary fasting', B: 'Seclusion in the mosque for worship', C: 'Night prayer', D: 'Giving charity' },
    correct: 'B',
    explanation: 'I\'tikaf is the act of secluding oneself in the mosque for worship, especially in the last 10 nights of Ramadan.',
  },
  {
    id: 'gi-137',
    category: 'general',
    question: 'Laylatul Qadr is better than how many months?',
    options: { A: '12 months', B: '100 months', C: '1000 months', D: '10 months' },
    correct: 'C',
    explanation: 'Allah says in the Quran: "Laylatul Qadr is better than a thousand months." (97:3)',
  },
  {
    id: 'gi-138',
    category: 'general',
    question: 'What is recommended to say excessively on Laylatul Qadr?',
    options: {
      A: 'Subhanallah 100 times',
      B: 'Allahumma innaka \'afuwwun tuhibbul \'afwa fa\'fu \'anni',
      C: 'La ilaha illallah 1000 times',
      D: 'Bismillah repeatedly',
    },
    correct: 'B',
    explanation: 'Aisha (RA) asked what du\'a to say on Laylatul Qadr, and the Prophet ﷺ taught her: "Allahumma innaka \'afuwwun tuhibbul \'afwa fa\'fu \'anni" (O Allah, You are Pardoning, You love to pardon, so pardon me).',
  },
  {
    id: 'gi-139',
    category: 'general',
    question: 'What does fasting teach Muslims?',
    options: { A: 'How to cook food', B: 'Patience, gratitude, and empathy for the poor', C: 'How to save money', D: 'Social skills' },
    correct: 'B',
    explanation: 'Fasting cultivates patience (sabr), gratitude to Allah, and empathy for those who go without food regularly.',
  },
  {
    id: 'gi-140',
    category: 'general',
    question: 'Who is exempt from fasting during Ramadan?',
    options: {
      A: 'Elderly, sick, pregnant, nursing, travelling — all with valid reasons',
      B: 'Only the elderly',
      C: 'Only the sick',
      D: 'No one is exempt',
    },
    correct: 'A',
    explanation: 'Those who are ill, elderly, pregnant, nursing, or travelling have valid exemptions. They must make up missed fasts or pay fidyah.',
  },

  // === MISCELLANEOUS ===
  {
    id: 'gi-141',
    category: 'general',
    question: 'What is Islamic jurisprudence (law) called?',
    options: { A: 'Tafsir', B: 'Hadith', C: 'Fiqh', D: 'Aqidah' },
    correct: 'C',
    explanation: 'Fiqh is Islamic jurisprudence — the human understanding and application of Shariah (Islamic law).',
  },
  {
    id: 'gi-142',
    category: 'general',
    question: 'What are the four major schools of Islamic jurisprudence?',
    options: {
      A: 'Hanafi, Maliki, Shafi\'i, Hanbali',
      B: 'Hanafi, Maliki, Ja\'fari, Ismaili',
      C: 'Shafi\'i, Hanbali, Zaidi, Ibadi',
      D: 'Maliki, Hanafi, Sufi, Salafi',
    },
    correct: 'A',
    explanation: 'The four Sunni schools of jurisprudence (madhabs) are: Hanafi, Maliki, Shafi\'i, and Hanbali.',
  },
  {
    id: 'gi-143',
    category: 'general',
    question: 'What does "Sunnah" mean?',
    options: { A: 'The Quran', B: 'The Prophet\'s ﷺ way, practice, and example', C: 'Obligatory acts', D: 'Islamic law' },
    correct: 'B',
    explanation: 'Sunnah refers to the Prophet\'s ﷺ way of life, including his sayings, actions, and tacit approvals.',
  },
  {
    id: 'gi-144',
    category: 'general',
    question: 'What is the Arabic term for the Islamic way of life / Islamic law?',
    options: { A: 'Fiqh', B: 'Sunnah', C: 'Shariah', D: 'Aqidah' },
    correct: 'C',
    explanation: 'Shariah literally means "the path to water." It refers to the divine guidance and Islamic way of life from the Quran and Sunnah.',
  },
  {
    id: 'gi-145',
    category: 'general',
    question: 'What is "Du\'a"?',
    options: { A: 'Obligatory prayer', B: 'Supplication / calling upon Allah', C: 'Fasting', D: 'Charity' },
    correct: 'B',
    explanation: 'Du\'a is supplication — directly calling upon Allah to ask for help, guidance, or anything one needs. The Prophet ﷺ called it "the essence of worship."',
  },
  {
    id: 'gi-146',
    category: 'general',
    question: 'What does "Jihad" primarily mean in Arabic?',
    options: { A: 'War', B: 'Striving and struggling in the way of Allah', C: 'Prayer', D: 'Fasting' },
    correct: 'B',
    explanation: 'Jihad means striving or struggling. The "greater jihad" is the internal struggle against one\'s own desires and ego.',
  },
  {
    id: 'gi-147',
    category: 'general',
    question: 'What is the term for the consensus of Islamic scholars?',
    options: { A: 'Qiyas', B: 'Ijtihad', C: 'Ijma', D: 'Fatwa' },
    correct: 'C',
    explanation: 'Ijma is the consensus of Islamic scholars on a ruling. It is one of the four sources of Islamic law.',
  },
  {
    id: 'gi-148',
    category: 'general',
    question: 'What is the Islamic term for the Friday sermon?',
    options: { A: 'Adhan', B: 'Khutbah', C: 'Tasbih', D: 'Du\'a' },
    correct: 'B',
    explanation: 'The Khutbah is the sermon delivered by the imam before the Friday Jumu\'ah prayer.',
  },
  {
    id: 'gi-149',
    category: 'general',
    question: 'What does "Astaghfirullah" mean?',
    options: { A: 'Praise be to Allah', B: 'I seek forgiveness from Allah', C: 'Allah is the Greatest', D: 'In the name of Allah' },
    correct: 'B',
    explanation: '"Astaghfirullah" means "I seek forgiveness from Allah." It is said frequently as a form of repentance.',
  },
  {
    id: 'gi-150',
    category: 'general',
    question: 'What is the term for the Islamic pillar of social welfare — mandatory charity?',
    options: { A: 'Sadaqah', B: 'Waqf', C: 'Zakat', D: 'Fidyah' },
    correct: 'C',
    explanation: 'Zakat is the obligatory pillar of charity (2.5% of qualifying savings) that redistributes wealth to those in need.',
  },
]
