import type { QuizQuestion } from '@/types/musabaqah'

// Section 3: Aqeedah, Fiqh & History Questions (50)
// Correct answer distribution: A=12, B=13, C=13, D=12

export const HISTORY_QUESTIONS: QuizQuestion[] = [
  {
    id: 'hi-001',
    category: 'history',
    question: 'Tawhid primarily focuses on:',
    options: { A: 'Worship alone', B: 'Legal rulings', C: 'History', D: 'Allah\'s oneness in lordship, worship, and names' },
    correct: 'D',
    explanation: 'Tawhid covers three dimensions: Rububiyyah (Lordship), Uluhiyyah (worship), and Asma wa Sifat (names and attributes). All three must be affirmed for complete Tawhid.',
  },
  {
    id: 'hi-002',
    category: 'history',
    question: 'Shirk (associating partners with Allah) nullifies:',
    options: { A: 'Deeds', B: 'Wealth', C: 'Knowledge', D: 'Travel' },
    correct: 'A',
    explanation: 'The Qur\'an states: "If you commit shirk, your deeds will surely be lost." (Az-Zumar 39:65) — Tawhid is the foundation upon which all deeds are accepted.',
  },
  {
    id: 'hi-003',
    category: 'history',
    question: 'Which principle governs flexibility in Islamic law during genuine hardship?',
    options: { A: 'Hardship brings ease', B: 'Strictness', C: 'Cultural norms', D: 'Personal opinion' },
    correct: 'A',
    explanation: 'The Fiqh maxim "al-Mashaqqah tajlib al-tayseer" (hardship brings ease) is derived from the Qur\'an and grants concessions like shortening prayer during travel.',
  },
  {
    id: 'hi-004',
    category: 'history',
    question: 'Which source of Islamic law ranks immediately after the Qur\'an?',
    options: { A: 'Ijma', B: 'Qiyas', C: 'Sunnah', D: 'Culture' },
    correct: 'C',
    explanation: 'The Sunnah of the Prophet ﷺ is the second source of Islamic law. It explains, specifies, and expands upon the Qur\'an, and is binding on all Muslims.',
  },
  {
    id: 'hi-005',
    category: 'history',
    question: 'Which concept ensures unity in Islamic creed among Muslims?',
    options: { A: 'Fiqh', B: 'Aqeedah', C: 'History', D: 'Language' },
    correct: 'B',
    explanation: 'Aqeedah (creed/belief) is what unites Muslims across different cultures and schools of law — the shared foundation of belief in Allah, His angels, books, messengers, and the Last Day.',
  },
  {
    id: 'hi-006',
    category: 'history',
    question: 'Which Caliph officially compiled the Qur\'an into a single standardised Mushaf?',
    options: { A: 'Abu Bakr', B: 'Umar', C: 'Uthman', D: 'Ali' },
    correct: 'C',
    explanation: 'Caliph Uthman ibn Affan (RA) standardised the Qur\'an into one authoritative Mushaf around 650 CE after differences in dialect emerged. Abu Bakr had earlier collected it from various materials.',
  },
  {
    id: 'hi-007',
    category: 'history',
    question: 'Ijma in Islamic jurisprudence refers to:',
    options: { A: 'Personal opinion', B: 'Government law', C: 'Culture', D: 'Scholarly consensus' },
    correct: 'D',
    explanation: 'Ijma (consensus) is the agreement of Muslim scholars of a given era on a legal ruling. It is the third source of Islamic law after the Qur\'an and Sunnah.',
  },
  {
    id: 'hi-008',
    category: 'history',
    question: 'Qiyas in Islamic law means:',
    options: { A: 'Revelation', B: 'Analogy', C: 'Tradition', D: 'Consensus' },
    correct: 'B',
    explanation: 'Qiyas is analogical reasoning — extending a known ruling to a new situation by identifying a shared underlying cause (illah). It is the fourth source of Sunni Islamic law.',
  },
  {
    id: 'hi-009',
    category: 'history',
    question: 'What is the overarching goal underlying all Shariah rulings?',
    options: { A: 'Benefit and harm prevention', B: 'Difficulty', C: 'Control', D: 'Culture' },
    correct: 'A',
    explanation: 'The Maqasid al-Shariah (objectives of Islamic law) aim to protect five essentials: religion, life, intellect, lineage, and wealth — all centred on benefit and preventing harm.',
  },
  {
    id: 'hi-010',
    category: 'history',
    question: 'Which act in Islam uniquely combines both belief and outward law?',
    options: { A: 'Faith', B: 'Prayer', C: 'Knowledge', D: 'Silence' },
    correct: 'B',
    explanation: 'Salah (prayer) is both an act of heart (intention, Khushu) and body (postures, timing). The Prophet ﷺ called it the pillar of religion — anchoring both faith and legal practice.',
  },
  {
    id: 'hi-011',
    category: 'history',
    question: 'What distinguishes Islamic monotheism from philosophical monism?',
    options: { A: 'Divine unity', B: 'Moral law', C: 'Creation', D: 'Absolute transcendence with attributes' },
    correct: 'D',
    explanation: 'Unlike philosophical monism (all is one), Islamic Tawhid affirms that Allah is entirely distinct from creation while simultaneously possessing real, perfect attributes like knowledge and mercy.',
  },
  {
    id: 'hi-012',
    category: 'history',
    question: 'Which concept in Islamic belief ensures ultimate accountability for all actions?',
    options: { A: 'Rizq', B: 'Qadr', C: 'Akhirah', D: 'Shura' },
    correct: 'C',
    explanation: 'Belief in the Akhirah (the Hereafter) — including resurrection, judgement, Paradise, and Hell — is one of the six pillars of faith and motivates ethical behaviour in this life.',
  },
  {
    id: 'hi-013',
    category: 'history',
    question: 'In Islamic governance, leadership is primarily viewed as:',
    options: { A: 'Privilege', B: 'Authority', C: 'Responsibility and trust', D: 'Honour' },
    correct: 'C',
    explanation: 'The Prophet ﷺ called leadership an "amanah" (trust). He warned that those who seek power for its own sake are unfit for it. Leadership is a duty to serve, not a privilege to enjoy.',
  },
  {
    id: 'hi-014',
    category: 'history',
    question: 'Which principle prevents extremism in Islamic religious practice?',
    options: { A: 'Moderation (Wasatiyyah)', B: 'Innovation', C: 'Seclusion', D: 'Rigidity' },
    correct: 'A',
    explanation: 'The Qur\'an describes Muslims as "a middle nation" (Ummah Wasatan, Al-Baqarah 2:143). Wasatiyyah — moderation between extremes — is a defining quality of authentic Islamic practice.',
  },
  {
    id: 'hi-015',
    category: 'history',
    question: 'In Islamic law, which category of actions is morally neutral unless the intention changes it?',
    options: { A: 'Haram', B: 'Fard', C: 'Mubah', D: 'Makruh' },
    correct: 'C',
    explanation: 'Mubah (permissible) actions are morally neutral — sleeping, eating, walking. With good intention (like eating to have strength to worship), they can become acts of worship.',
  },
  {
    id: 'hi-016',
    category: 'history',
    question: 'Which Islamic principle governs how Muslims interact with non-Muslims?',
    options: { A: 'Hostility', B: 'Justice and fairness', C: 'Isolation', D: 'Superiority' },
    correct: 'B',
    explanation: 'The Qur\'an commands: "Allah does not forbid you from being kind and just to those who have not fought you over religion." (Al-Mumtahanah 60:8) — justice and kindness are the baseline.',
  },
  {
    id: 'hi-017',
    category: 'history',
    question: 'What is the primary role of Islamic scholars?',
    options: { A: 'Govern society', B: 'Enforce laws', C: 'Issue punishments', D: 'Preserve and explain knowledge' },
    correct: 'D',
    explanation: 'Scholars are the "inheritors of the prophets" (Abu Dawud). Their role is to transmit, explain, and apply the knowledge of the Qur\'an and Sunnah — not to govern or punish.',
  },
  {
    id: 'hi-018',
    category: 'history',
    question: 'Which Islamic belief rejects fatalism while still affirming divine decree?',
    options: { A: 'Complete free will', B: 'Absolute determinism', C: 'Balance between choice and decree', D: 'Human control' },
    correct: 'C',
    explanation: 'Authentic Aqeedah holds that Allah knows all things and decrees them, while humans have real choice and responsibility. This balance avoids both fatalism and the denial of Qadr.',
  },
  {
    id: 'hi-019',
    category: 'history',
    question: 'Which historical event marked the beginning of the Islamic (Hijri) calendar?',
    options: { A: 'First revelation', B: 'Conquest of Makkah', C: 'Migration to Madinah', D: 'Farewell sermon' },
    correct: 'C',
    explanation: 'Caliph Umar (RA) established the Hijri calendar to begin from the Prophet\'s migration (Hijrah) to Madinah in 622 CE — a pivotal moment marking the birth of the Muslim community.',
  },
  {
    id: 'hi-020',
    category: 'history',
    question: 'Which concept ensures ethical economic behaviour in Islam?',
    options: { A: 'Accountability before Allah', B: 'Profit maximization', C: 'Interest-based growth', D: 'Market dominance' },
    correct: 'A',
    explanation: 'Islamic economics is governed by the awareness that all wealth belongs to Allah, every transaction is witnessed by Him, and one will be asked on the Day of Judgement how wealth was earned and spent.',
  },
  {
    id: 'hi-021',
    category: 'history',
    question: 'Which type of knowledge is a personal religious obligation (Fard Ayn) on every Muslim?',
    options: { A: 'Astronomy', B: 'Medicine', C: 'Essential religious knowledge', D: 'Philosophy' },
    correct: 'C',
    explanation: 'Every Muslim must learn enough religion to worship Allah correctly — the pillars of faith, prayer, fasting, and basic halal/haram. This is Fard Ayn (individual obligation).',
  },
  {
    id: 'hi-022',
    category: 'history',
    question: 'Which Islamic value regulates personal freedom?',
    options: { A: 'Desire', B: 'Cultural norms', C: 'Moral responsibility', D: 'Authority' },
    correct: 'C',
    explanation: 'In Islam, personal freedom is bounded by moral responsibility — both to Allah and to others. Freedom without accountability leads to harm, which is why Shariah balances rights with duties.',
  },
  {
    id: 'hi-023',
    category: 'history',
    question: 'Which act best reflects sincerity (Ikhlas) in worship?',
    options: { A: 'Public charity', B: 'Leadership', C: 'Debate', D: 'Hidden good deeds' },
    correct: 'D',
    explanation: 'The Prophet ﷺ described a man who gives charity so secretly that his left hand does not know what his right hand spends — as one of the seven who receive Allah\'s shade on Judgement Day.',
  },
  {
    id: 'hi-024',
    category: 'history',
    question: 'Which principle prevents misuse of religious texts in Islamic scholarship?',
    options: { A: 'Literalism only', B: 'Contextual understanding', C: 'Personal opinion', D: 'Cultural influence' },
    correct: 'B',
    explanation: 'Understanding Asbab al-Nuzul, Nasikh, Ijaz, and proper Usul (principles) prevents misapplication of texts. Context ensures the Qur\'an and Hadith are applied as Allah and the Prophet ﷺ intended.',
  },
  {
    id: 'hi-025',
    category: 'history',
    question: 'Which trait strengthens trust within a Muslim society?',
    options: { A: 'Honesty', B: 'Intelligence', C: 'Wealth', D: 'Silence' },
    correct: 'A',
    explanation: 'The Prophet ﷺ was known as Al-Amin (the Trustworthy) before prophethood. Honesty in speech and dealings is the backbone of societal trust and a key prophetic character trait.',
  },
  {
    id: 'hi-026',
    category: 'history',
    question: 'Which concept defines lawful earning in Islam?',
    options: { A: 'Profit', B: 'Competition', C: 'Halal livelihood', D: 'Accumulation' },
    correct: 'C',
    explanation: 'The Prophet ﷺ said no one has eaten better food than that earned by their own hands. Halal livelihood (Kasb Halal) means earning through permissible, honest, and non-exploitative means.',
  },
  {
    id: 'hi-027',
    category: 'history',
    question: 'Which ethical principle governs disagreement in Islam?',
    options: { A: 'Victory', B: 'Respect and wisdom', C: 'Silence', D: 'Authority' },
    correct: 'B',
    explanation: 'The Qur\'an commands: "Call to the way of your Lord with wisdom and good advice, and argue with them in the best manner." (An-Nahl 16:125) — truth must be conveyed respectfully.',
  },
  {
    id: 'hi-028',
    category: 'history',
    question: 'Which action best reflects gratitude (Shukr) to Allah?',
    options: { A: 'Complaining less', B: 'Accumulating wealth', C: 'Isolation', D: 'Using blessings responsibly' },
    correct: 'D',
    explanation: 'True Shukr is not just saying "Alhamdulillah" — it is using Allah\'s blessings (health, wealth, time) in ways that please Him. The Qur\'an says Allah increases those who are grateful.',
  },
  {
    id: 'hi-029',
    category: 'history',
    question: 'Which belief protects a Muslim from despair during hardship?',
    options: { A: 'Hope in divine mercy', B: 'Patience', C: 'Knowledge', D: 'Silence' },
    correct: 'A',
    explanation: 'The Qur\'an states: "Do not despair of Allah\'s mercy; indeed, Allah forgives all sins." (Az-Zumar 39:53). Hope in divine mercy is commanded — despair itself is a sin.',
  },
  {
    id: 'hi-030',
    category: 'history',
    question: 'Which concept links acts of worship with daily life in Islam?',
    options: { A: 'Ritualism', B: 'Intention', C: 'Innovation', D: 'Seclusion' },
    correct: 'B',
    explanation: 'Niyyah (intention) is what transforms ordinary acts into worship. Eating, sleeping, working — all become acts of devotion when done with the intention of pleasing Allah.',
  },
  {
    id: 'hi-031',
    category: 'history',
    question: 'Which behavior directly contradicts Islamic brotherhood?',
    options: { A: 'Advice', B: 'Forgiveness', C: 'Charity', D: 'Envy' },
    correct: 'D',
    explanation: 'The Prophet ﷺ warned: "Beware of envy, for it consumes good deeds as fire consumes wood." (Abu Dawud) — Hasad (envy) destroys the envious person and breaks community bonds.',
  },
  {
    id: 'hi-032',
    category: 'history',
    question: 'Which principle ensures balance between worldly life (dunya) and the hereafter (akhirah)?',
    options: { A: 'Withdrawal', B: 'Neglect', C: 'Moderation', D: 'Excess' },
    correct: 'C',
    explanation: 'The Qur\'an instructs: "Do not forget your share of the world." (Al-Qasas 28:77) — Islam encourages engagement with the world while keeping the hereafter as the ultimate priority.',
  },
  {
    id: 'hi-033',
    category: 'history',
    question: 'Which moral quality most leads to societal harmony in Islam?',
    options: { A: 'Mercy', B: 'Competition', C: 'Control', D: 'Isolation' },
    correct: 'A',
    explanation: 'The Prophet ﷺ said: "The merciful will be shown mercy by the All-Merciful." Mercy between people — in families, communities, and governance — is the key to harmonious societies.',
  },
  {
    id: 'hi-034',
    category: 'history',
    question: 'Which act transforms ordinary daily habits into acts of worship?',
    options: { A: 'Routine', B: 'Intention', C: 'Culture', D: 'Custom' },
    correct: 'B',
    explanation: 'With sincere intention for the sake of Allah, eating, sleeping, working, and even resting can all become forms of ibadah — this is what makes Islam a complete way of life.',
  },
  {
    id: 'hi-035',
    category: 'history',
    question: 'Which concept defines justice (Adl) in Islamic ethics?',
    options: { A: 'Equality in all cases', B: 'Authority', C: 'Power', D: 'Placing things in their rightful place' },
    correct: 'D',
    explanation: 'Islamic justice is not blind equality but Adl — giving each person and situation its due. This includes just distribution of wealth, fair rulings, and equitable treatment of all.',
  },
  {
    id: 'hi-036',
    category: 'history',
    question: 'Which attitude corrupts otherwise good deeds?',
    options: { A: 'Patience', B: 'Showing off (Riya)', C: 'Humility', D: 'Gratitude' },
    correct: 'B',
    explanation: 'Riya (showing off) is called "minor shirk" by the Prophet ﷺ. Performing acts of worship to be seen by people rather than for Allah nullifies the spiritual benefit and reward.',
  },
  {
    id: 'hi-037',
    category: 'history',
    question: 'Which responsibility applies equally to both rulers and ordinary citizens in Islam?',
    options: { A: 'Wealth', B: 'Authority', C: 'Privilege', D: 'Accountability' },
    correct: 'D',
    explanation: 'The Prophet ﷺ said: "Each of you is a shepherd and each is responsible for his flock." (Bukhari, Muslim) — all Muslims, from leaders to individuals, are accountable for their roles.',
  },
  {
    id: 'hi-038',
    category: 'history',
    question: 'Which principle guides ethical decision-making in Islam?',
    options: { A: 'Personal desire', B: 'Social pressure', C: 'Divine guidance', D: 'Majority opinion' },
    correct: 'C',
    explanation: 'Islamic ethics is theocentric — decisions are made by asking "What does Allah command?" Popularity, cultural pressure, or personal desire do not override divine guidance.',
  },
  {
    id: 'hi-039',
    category: 'history',
    question: 'Which quality most strengthens a believer\'s faith during times of hardship?',
    options: { A: 'Patience with trust in Allah', B: 'Knowledge alone', C: 'Wealth', D: 'Isolation' },
    correct: 'A',
    explanation: 'Sabr (patience) combined with Tawakkul (reliance on Allah) is the believer\'s shield during hardship. The Qur\'an promises that Allah is with those who are patient (Al-Baqarah 2:153).',
  },
  {
    id: 'hi-040',
    category: 'history',
    question: 'Which Islamic practice promotes mental and spiritual well-being?',
    options: { A: 'Suppression', B: 'Gratitude and remembrance', C: 'Withdrawal', D: 'Silence' },
    correct: 'B',
    explanation: 'The Qur\'an says: "Verily, in the remembrance of Allah do hearts find rest." (Ar-Ra\'d 13:28) — dhikr and gratitude are the spiritual remedies the Qur\'an prescribes for anxiety.',
  },
  {
    id: 'hi-041',
    category: 'history',
    question: 'Which principle governs environmental responsibility in Islam?',
    options: { A: 'Ownership', B: 'Exploitation', C: 'Profit', D: 'Stewardship (Khilafah)' },
    correct: 'D',
    explanation: 'Allah appointed humans as Khalifah (stewards) on earth. Resources belong to Allah — we are trustees, not owners. The Prophet ﷺ prohibited wasteful use of even water.',
  },
  {
    id: 'hi-042',
    category: 'history',
    question: 'Which belief encourages humility in a Muslim?',
    options: { A: 'Wealth accumulation', B: 'Awareness of accountability', C: 'Authority', D: 'Knowledge alone' },
    correct: 'B',
    explanation: 'Remembering that every deed is recorded and will be presented before Allah on Judgement Day keeps the believer humble — no one can be arrogant knowing they will be fully accountable.',
  },
  {
    id: 'hi-043',
    category: 'history',
    question: 'Which Islamic value discourages injustice even when it is against oneself?',
    options: { A: 'Loyalty', B: 'Truthfulness', C: 'Justice', D: 'Patience' },
    correct: 'C',
    explanation: 'The Qur\'an commands: "Be persistently standing firmly for justice, witnesses for Allah, even if it be against yourselves or parents and relatives." (An-Nisa 4:135)',
  },
  {
    id: 'hi-044',
    category: 'history',
    question: 'Which factors make acts of worship valid and accepted in Islam?',
    options: { A: 'Intention and correctness', B: 'Quantity', C: 'Public recognition', D: 'Difficulty' },
    correct: 'A',
    explanation: 'Scholars state that worship must meet two conditions to be accepted: sincerity of intention (Ikhlas) and correctness of method (Mutaba\'ah — following the Prophet\'s example).',
  },
  {
    id: 'hi-045',
    category: 'history',
    question: 'Which principle governs family relations in Islam?',
    options: { A: 'Authority', B: 'Mercy and responsibility', C: 'Control', D: 'Tradition' },
    correct: 'B',
    explanation: 'The Qur\'an describes marriage as built on "mawaddah wa rahmah" — love and mercy (Ar-Rum 30:21). Family in Islam is a covenant of mutual responsibility, not hierarchy or control.',
  },
  {
    id: 'hi-046',
    category: 'history',
    question: 'Which trait leads to spiritual growth in Islam?',
    options: { A: 'Self-admiration', B: 'Isolation', C: 'Debate', D: 'Self-accountability' },
    correct: 'D',
    explanation: 'Muhasabah (self-accountability) — regularly examining one\'s intentions, actions, and sins — is a key tool of spiritual development taught by the Prophet ﷺ and the righteous predecessors.',
  },
  {
    id: 'hi-047',
    category: 'history',
    question: 'Which concept protects Islamic ethics from moral relativism?',
    options: { A: 'Cultural norms', B: 'Divine revelation', C: 'Majority opinion', D: 'Custom' },
    correct: 'B',
    explanation: 'Islamic morality is grounded in divine revelation — not human consensus, culture, or shifting social norms. What Allah has declared right remains right regardless of popular opinion.',
  },
  {
    id: 'hi-048',
    category: 'history',
    question: 'Which Islamic value governs the use of power and authority?',
    options: { A: 'Justice and accountability', B: 'Control', C: 'Dominance', D: 'Expansion' },
    correct: 'A',
    explanation: 'Power in Islam is an amanah (trust). The Prophet ﷺ warned that on Judgement Day, every leader will be asked about those under their care. Power used unjustly becomes a burden, not a honour.',
  },
  {
    id: 'hi-049',
    category: 'history',
    question: 'Which attitude leads to lasting success according to Islamic teachings?',
    options: { A: 'Sincerity and perseverance', B: 'Pride', C: 'Speed', D: 'Authority' },
    correct: 'A',
    explanation: 'The Qur\'an links success (Falah) to those who purify themselves and remember Allah. Sincere effort combined with perseverance — not pride in results — defines the Muslim path to success.',
  },
  {
    id: 'hi-050',
    category: 'history',
    question: 'Which concept unites belief, worship, and ethics in Islam?',
    options: { A: 'Knowledge', B: 'Culture', C: 'Law', D: 'Taqwa' },
    correct: 'D',
    explanation: 'Taqwa (God-consciousness) is the thread that unites Iman (belief), Ibadah (worship), and Akhlaq (ethics). The Qur\'an says the most honoured in Allah\'s sight is the most God-conscious (Al-Hujurat 49:13).',
  },
]
