import type { QuizQuestion } from '@/types/musabaqah'

export const PROPHET_STORIES_QUESTIONS: QuizQuestion[] = [
  // === PROPHET ADAM ===
  {
    id: 'ps-001',
    category: 'prophets',
    question: 'Who was the first human being created by Allah?',
    options: { A: 'Nuh', B: 'Ibrahim', C: 'Adam', D: 'Idris' },
    correct: 'C',
    explanation: 'Adam (peace be upon him) was the first human being, created by Allah from clay.',
  },
  {
    id: 'ps-002',
    category: 'prophets',
    question: 'What was Adam (AS) created from?',
    options: { A: 'Water', B: 'Fire', C: 'Clay / Earth', D: 'Light' },
    correct: 'C',
    explanation: 'Allah created Adam from clay (earth/dust). Allah breathed life into him and honoured him among His creation.',
  },
  {
    id: 'ps-003',
    category: 'prophets',
    question: 'What was the name of Adam\'s wife?',
    options: { A: 'Maryam', B: 'Khadijah', C: 'Asiyah', D: 'Hawwa (Eve)' },
    correct: 'D',
    explanation: 'Hawwa (Eve) was the wife of Adam. She was created from Adam as his companion.',
  },
  {
    id: 'ps-004',
    category: 'prophets',
    question: 'Which creature refused to bow to Adam when commanded by Allah?',
    options: { A: 'A jinn', B: 'An angel', C: 'Iblis (Shaytan)', D: 'A snake' },
    correct: 'C',
    explanation: 'Iblis refused to prostrate to Adam out of arrogance, saying: "I am better than him; You created me from fire and him from clay." He was expelled.',
  },
  {
    id: 'ps-005',
    category: 'prophets',
    question: 'What did Allah teach Adam that the angels did not know?',
    options: { A: 'How to pray', B: 'The names of all things', C: 'How to build', D: 'The Quran' },
    correct: 'B',
    explanation: 'Allah taught Adam the names of all things. This knowledge distinguished Adam, and the angels acknowledged they had no knowledge except what Allah taught them.',
  },
  {
    id: 'ps-006',
    category: 'prophets',
    question: 'What was the name of Adam\'s two sons whose story is in the Quran?',
    options: { A: 'Ismail and Ishaq', B: 'Habil (Abel) and Qabil (Cain)', C: 'Dawud and Sulayman', D: 'Harun and Musa' },
    correct: 'B',
    explanation: 'The story of Habil (Abel) and Qabil (Cain) is told in Surah Al-Maidah. Qabil killed Habil — the first murder in human history.',
  },
  {
    id: 'ps-007',
    category: 'prophets',
    question: 'Where did Adam and Hawwa live before coming to Earth?',
    options: { A: 'The mountains', B: 'Jannah (Paradise)', C: 'Mecca', D: 'Jerusalem' },
    correct: 'B',
    explanation: 'Adam and Hawwa lived in Jannah (Paradise) before being sent to Earth. They were sent down after eating from the forbidden tree.',
  },
  {
    id: 'ps-008',
    category: 'prophets',
    question: 'After Adam repented to Allah, what did Allah do?',
    options: { A: 'Punished him', B: 'Ignored him', C: 'Accepted his repentance and guided him', D: 'Sent him back to Paradise immediately' },
    correct: 'C',
    explanation: 'Adam sincerely repented, saying: "Our Lord, we have wronged ourselves..." (7:23). Allah accepted his repentance and guided him.',
  },

  // === PROPHET IDRIS ===
  {
    id: 'ps-009',
    category: 'prophets',
    question: 'Prophet Idris is believed to be associated with which skill?',
    options: { A: 'Shipbuilding', B: 'Writing and astronomy', C: 'Ironwork', D: 'Farming' },
    correct: 'B',
    explanation: 'Idris (Enoch) is associated with writing, astronomy, and knowledge. He is mentioned as a truthful prophet in the Quran.',
  },
  {
    id: 'ps-010',
    category: 'prophets',
    question: 'What does the Quran say about Prophet Idris\'s status?',
    options: { A: 'He was lowered in rank', B: 'He was raised to a high place by Allah', C: 'He was the first prophet', D: 'He built the Ka\'bah' },
    correct: 'B',
    explanation: 'The Quran says: "And We raised him to a high place." (19:57) Idris is honoured with an elevated status.',
  },

  // === PROPHET NUH (NOAH) ===
  {
    id: 'ps-011',
    category: 'prophets',
    question: 'How long did Prophet Nuh call his people before the flood?',
    options: { A: '40 years', B: '100 years', C: '950 years', D: '500 years' },
    correct: 'C',
    explanation: 'The Quran states that Nuh remained among his people for 950 years, calling them to worship Allah alone (29:14).',
  },
  {
    id: 'ps-012',
    category: 'prophets',
    question: 'What did Allah command Prophet Nuh to build?',
    options: { A: 'A temple', B: 'A city wall', C: 'An ark (ship)', D: 'A tower' },
    correct: 'C',
    explanation: 'Allah commanded Nuh to build the Ark (Safinah) to save the believers and pairs of animals from the great flood.',
  },
  {
    id: 'ps-013',
    category: 'prophets',
    question: 'Which of Prophet Nuh\'s sons refused to board the ark and drowned?',
    options: { A: 'Shem', B: 'Ham', C: 'Kan\'an', D: 'Yafith' },
    correct: 'C',
    explanation: 'Nuh\'s son Kan\'an refused to board the ark, saying he would climb a mountain. He was among those who drowned.',
  },
  {
    id: 'ps-014',
    category: 'prophets',
    question: 'Why did the flood come during Prophet Nuh\'s time?',
    options: { A: 'Heavy rainfall season', B: 'His people disbelieved and rejected him', C: 'Nuh prayed for it', D: 'An earthquake caused it' },
    correct: 'B',
    explanation: 'The flood was Allah\'s punishment for the people who rejected Nuh\'s call to monotheism for hundreds of years.',
  },
  {
    id: 'ps-015',
    category: 'prophets',
    question: 'What title is Prophet Nuh given in the Quran?',
    options: { A: 'Khalilullah', B: 'Kalimullah', C: 'Shakirun (Grateful)', D: 'Ruhullah' },
    correct: 'C',
    explanation: 'The Quran refers to Nuh as a "shakirun" (thankful/grateful servant). He is also called the "second Adam" as humanity repopulated from his children.',
  },
  {
    id: 'ps-016',
    category: 'prophets',
    question: 'Where did Nuh\'s ark come to rest after the flood?',
    options: { A: 'Mount Sinai', B: 'Mount Judi', C: 'Mount Arafah', D: 'Mount Uhud' },
    correct: 'B',
    explanation: 'The Quran says: "And it (the ark) came to rest upon (the mountain) Al-Judi." (11:44) Mount Judi is believed to be in modern Turkey.',
  },
  {
    id: 'ps-017',
    category: 'prophets',
    question: 'Who were the people of Nuh\'s main idols?',
    options: { A: 'Lata, Uzza, Manat', B: 'Wadd, Suwa\', Yaghuth, Ya\'uq, Nasr', C: 'Hubal, Jibt, Taghut', D: 'Baal, Dagon, Moloch' },
    correct: 'B',
    explanation: 'Nuh\'s people worshipped five main idols named in the Quran: Wadd, Suwa\', Yaghuth, Ya\'uq, and Nasr. (71:23)',
  },

  // === PROPHET HUD ===
  {
    id: 'ps-018',
    category: 'prophets',
    question: 'Prophet Hud was sent to which people?',
    options: { A: 'Thamud', B: 'The people of Madyan', C: '\'Ad', D: 'The people of Lut' },
    correct: 'C',
    explanation: 'Hud was sent to the \'Ad — a powerful ancient Arab people known for their great physical strength and towering buildings.',
  },
  {
    id: 'ps-019',
    category: 'prophets',
    question: 'How were the people of \'Ad destroyed?',
    options: { A: 'A great flood', B: 'A mighty wind / hurricane for 7 nights and 8 days', C: 'An earthquake', D: 'Fire from the sky' },
    correct: 'B',
    explanation: 'The \'Ad were destroyed by a violent wind that Allah sent against them for seven nights and eight days. (69:6-7)',
  },

  // === PROPHET SALIH ===
  {
    id: 'ps-020',
    category: 'prophets',
    question: 'Prophet Salih was sent to which people?',
    options: { A: '\'Ad', B: 'Thamud', C: 'Madyan', D: 'Babylon' },
    correct: 'B',
    explanation: 'Salih was sent to the Thamud, who lived in the region of Al-Hijr (northwest Arabia). They were known for carving homes into mountains.',
  },
  {
    id: 'ps-021',
    category: 'prophets',
    question: 'What was the miracle given to Prophet Salih?',
    options: { A: 'A staff that parted water', B: 'A she-camel from the rock', C: 'Fire that did not burn', D: 'Healing the sick' },
    correct: 'B',
    explanation: 'Salih\'s people demanded a miracle, so Allah brought forth a she-camel from a rock. The people were told not to harm her — but they killed her.',
  },
  {
    id: 'ps-022',
    category: 'prophets',
    question: 'How were the Thamud destroyed after killing the she-camel?',
    options: { A: 'A great flood', B: 'A thunderbolt / mighty blast', C: 'A windstorm', D: 'Fire' },
    correct: 'B',
    explanation: 'The Thamud were destroyed by a mighty thunderbolt (thunderous blast) sent by Allah three days after they killed the she-camel.',
  },

  // === PROPHET IBRAHIM (ABRAHAM) ===
  {
    id: 'ps-023',
    category: 'prophets',
    question: 'What special title was Prophet Ibrahim given?',
    options: { A: 'Kalimullah', B: 'Ruhullah', C: 'Khalilullah (Friend of Allah)', D: 'Habibullah' },
    correct: 'C',
    explanation: 'Ibrahim (AS) was given the title "Khalilullah" — the intimate friend of Allah. This is mentioned in Surah An-Nisa (4:125).',
  },
  {
    id: 'ps-024',
    category: 'prophets',
    question: 'What did young Ibrahim do to the idols of his people?',
    options: { A: 'He prayed to them', B: 'He smashed them all except the largest', C: 'He hid them', D: 'He built them' },
    correct: 'B',
    explanation: 'Ibrahim broke all the idols except the largest, then hung the axe on it to challenge his people and prove idols cannot defend themselves.',
  },
  {
    id: 'ps-025',
    category: 'prophets',
    question: 'How did Allah protect Ibrahim when his people threw him into the fire?',
    options: { A: 'He was rescued by angels', B: 'He jumped out', C: 'Allah commanded the fire to be cool and safe for him', D: 'Rain put the fire out' },
    correct: 'C',
    explanation: 'Allah commanded: "O fire, be cool and safe for Ibrahim!" (21:69) The fire did not harm him — it was a miracle.',
  },
  {
    id: 'ps-026',
    category: 'prophets',
    question: 'Who was the king that debated with Ibrahim about the power of Allah?',
    options: { A: 'Pharaoh', B: 'Namrud (Nimrod)', C: 'Goliath', D: 'Caesar' },
    correct: 'B',
    explanation: 'Namrud (Nimrod) debated with Ibrahim, claiming he too could give life and death. Ibrahim challenged him with the rising and setting of the sun.',
  },
  {
    id: 'ps-027',
    category: 'prophets',
    question: 'Who did Ibrahim leave in the valley of Mecca with a baby?',
    options: { A: 'His wife Sarah with Ishaq', B: 'His wife Hajar with baby Ismail', C: 'His son Yaqub', D: 'His brother' },
    correct: 'B',
    explanation: 'Ibrahim left his wife Hajar and their infant son Ismail in the barren valley of Mecca by Allah\'s command. This act of trust led to the miracle of Zamzam.',
  },
  {
    id: 'ps-028',
    category: 'prophets',
    question: 'What miraculous water spring appeared when Hajar searched for water for Ismail?',
    options: { A: 'The Nile', B: 'The Jordan River', C: 'Zamzam', D: 'The Euphrates' },
    correct: 'C',
    explanation: 'Zamzam water sprang up near baby Ismail\'s feet when Hajar was desperately searching for water. It still flows today.',
  },
  {
    id: 'ps-029',
    category: 'prophets',
    question: 'What great test did Ibrahim face involving his son?',
    options: { A: 'Leaving his son in the desert', B: 'Being commanded to sacrifice his son', C: 'Sending his son on Hajj', D: 'Teaching his son to build' },
    correct: 'B',
    explanation: 'Ibrahim saw in a dream that he was sacrificing his son. He prepared to carry it out, but Allah replaced the son with a ram and declared it a great test.',
  },
  {
    id: 'ps-030',
    category: 'prophets',
    question: 'Which son did Ibrahim build the Ka\'bah with?',
    options: { A: 'Ishaq (Isaac)', B: 'Yaqub (Jacob)', C: 'Ismail (Ishmael)', D: 'Yusuf (Joseph)' },
    correct: 'C',
    explanation: 'Ibrahim and his son Ismail built the Ka\'bah in Mecca as a house of worship for Allah. (Quran 2:127)',
  },
  {
    id: 'ps-031',
    category: 'prophets',
    question: 'What du\'a did Ibrahim make when he completed building the Ka\'bah?',
    options: {
      A: 'He asked for wealth',
      B: 'He asked Allah to send a prophet from his descendants and to accept the worship',
      C: 'He asked to return to his homeland',
      D: 'He asked for a long life',
    },
    correct: 'B',
    explanation: 'Ibrahim prayed: "Our Lord, send among them a messenger from themselves..." (2:129) This du\'a was answered with the sending of Prophet Muhammad ﷺ.',
  },
  {
    id: 'ps-032',
    category: 'prophets',
    question: 'What two sons were born to Ibrahim?',
    options: { A: 'Musa and Harun', B: 'Dawud and Sulayman', C: 'Ismail and Ishaq', D: 'Yusuf and Yaqub' },
    correct: 'C',
    explanation: 'Ibrahim had Ismail (Ishmael) with Hajar, and Ishaq (Isaac) with Sarah. Both sons became prophets.',
  },

  // === PROPHET LUT (LOT) ===
  {
    id: 'ps-033',
    category: 'prophets',
    question: 'Prophet Lut was sent to which people?',
    options: { A: 'The people of \'Ad', B: 'The people of Sodom', C: 'The people of Madyan', D: 'The people of Thamud' },
    correct: 'B',
    explanation: 'Lut was sent to the people of Sodom (Qawm Lut) who were engaged in indecency. He was a nephew of Prophet Ibrahim.',
  },
  {
    id: 'ps-034',
    category: 'prophets',
    question: 'Who came to Lut\'s home disguised as guests before his people were destroyed?',
    options: { A: 'Other prophets', B: 'Angels', C: 'Jinn', D: 'Merchants' },
    correct: 'B',
    explanation: 'Angels came to Lut disguised as handsome young men. His people acted indecently toward them, leading to the punishment.',
  },
  {
    id: 'ps-035',
    category: 'prophets',
    question: 'How were the people of Lut destroyed?',
    options: { A: 'A flood', B: 'A windstorm', C: 'Their cities were turned upside down and stones rained on them', D: 'A plague' },
    correct: 'C',
    explanation: 'Allah turned their cities upside down and rained upon them stones of hard clay. Lut and the believers were saved.',
  },
  {
    id: 'ps-036',
    category: 'prophets',
    question: 'Who was told not to look back when fleeing the destruction but disobeyed?',
    options: { A: 'Lut\'s daughter', B: 'Lut himself', C: 'Lut\'s wife', D: 'Lut\'s son' },
    correct: 'C',
    explanation: 'Lut\'s wife was among those who looked back and was destroyed. She had sided with her people against her husband.',
  },

  // === PROPHET ISMAIL ===
  {
    id: 'ps-037',
    category: 'prophets',
    question: 'Who was the mother of Prophet Ismail?',
    options: { A: 'Sarah', B: 'Hajar', C: 'Maryam', D: 'Asiyah' },
    correct: 'B',
    explanation: 'Hajar (Hagar) was the mother of Ismail. She was an Egyptian woman given to Ibrahim.',
  },
  {
    id: 'ps-038',
    category: 'prophets',
    question: 'The running between Safa and Marwa during Hajj commemorates which event?',
    options: { A: 'Ibrahim\'s search for water', B: 'Hajar\'s search for water for her son Ismail', C: 'Maryam\'s walk to give birth', D: 'Nuh\'s journey before the flood' },
    correct: 'B',
    explanation: 'Hajar ran seven times between the hills of Safa and Marwa searching for water for her baby Ismail. This is commemorated in Sa\'i during Hajj.',
  },
  {
    id: 'ps-039',
    category: 'prophets',
    question: 'Ismail (AS) is considered the ancestor of which people?',
    options: { A: 'The Jewish people', B: 'The Persian people', C: 'The Arab people', D: 'The Egyptian people' },
    correct: 'C',
    explanation: 'Ismail settled in Mecca and is considered the ancestor of the Arabs. Prophet Muhammad ﷺ is a descendant of Ismail.',
  },

  // === PROPHET YUSUF (JOSEPH) ===
  {
    id: 'ps-040',
    category: 'prophets',
    question: 'Which surah of the Quran tells the complete story of Prophet Yusuf?',
    options: { A: 'Surah Al-Kahf', B: 'Surah Yusuf', C: 'Surah Maryam', D: 'Surah Ibrahim' },
    correct: 'B',
    explanation: 'Surah Yusuf (Chapter 12) tells the complete story of Prophet Yusuf. Allah calls it "the best of stories" in the Quran.',
  },
  {
    id: 'ps-041',
    category: 'prophets',
    question: 'Who was the father of Prophet Yusuf?',
    options: { A: 'Ibrahim', B: 'Ishaq', C: 'Yaqub (Jacob)', D: 'Ismail' },
    correct: 'C',
    explanation: 'Yaqub (Jacob) was the father of Yusuf. Yaqub was the son of Ishaq, who was the son of Ibrahim.',
  },
  {
    id: 'ps-042',
    category: 'prophets',
    question: 'What did Yusuf see in his childhood dream?',
    options: { A: 'A great flood', B: 'Eleven stars, the sun, and moon bowing to him', C: 'A beautiful garden', D: 'Seven fat and seven thin cows' },
    correct: 'B',
    explanation: 'Young Yusuf dreamed that eleven stars, the sun, and the moon were prostrating to him. His father recognised it as a sign of greatness.',
  },
  {
    id: 'ps-043',
    category: 'prophets',
    question: 'What did Yusuf\'s brothers do to him out of jealousy?',
    options: { A: 'They burned his home', B: 'They threw him into a well', C: 'They exiled him to Egypt', D: 'They imprisoned him' },
    correct: 'B',
    explanation: 'Yusuf\'s brothers, jealous of their father\'s love for him, threw him into a well. They returned with a false story to their father.',
  },
  {
    id: 'ps-044',
    category: 'prophets',
    question: 'Who rescued Yusuf from the well?',
    options: { A: 'Angels', B: 'A caravan of travellers', C: 'Egyptian soldiers', D: 'His brother Benjamin' },
    correct: 'B',
    explanation: 'A caravan of travellers passed by, discovered Yusuf in the well, and took him to Egypt where he was sold as a slave.',
  },
  {
    id: 'ps-045',
    category: 'prophets',
    question: 'Who was Yusuf sold to in Egypt?',
    options: { A: 'The Pharaoh', B: 'A nobleman called Al-Aziz', C: 'A merchant', D: 'A soldier' },
    correct: 'B',
    explanation: 'Yusuf was sold to Al-Aziz, the chief minister (or treasurer) of Egypt. Al-Aziz told his wife to honour Yusuf.',
  },
  {
    id: 'ps-046',
    category: 'prophets',
    question: 'Why was Yusuf imprisoned in Egypt?',
    options: {
      A: 'He refused to bow to the Pharaoh',
      B: 'Al-Aziz\'s wife falsely accused him after he rejected her',
      C: 'He stole from the palace',
      D: 'He preached Islam openly',
    },
    correct: 'B',
    explanation: 'Al-Aziz\'s wife tried to seduce Yusuf; he refused. When caught, she falsely accused him. He was imprisoned despite his innocence.',
  },
  {
    id: 'ps-047',
    category: 'prophets',
    question: 'What special ability did Yusuf have?',
    options: { A: 'He could speak to animals', B: 'He could interpret dreams', C: 'He could heal the sick', D: 'He could control the wind' },
    correct: 'B',
    explanation: 'Yusuf was gifted with the interpretation of dreams — a gift from Allah. This gift led to his release from prison.',
  },
  {
    id: 'ps-048',
    category: 'prophets',
    question: 'What was the dream of the King of Egypt that Yusuf interpreted?',
    options: {
      A: 'A great flood coming',
      B: 'Seven fat cows eaten by seven thin cows, and seven green ears of corn and seven dry ones',
      C: 'A bright star falling',
      D: 'A river running dry',
    },
    correct: 'B',
    explanation: 'The King dreamed of seven fat cows devoured by seven thin ones, and seven green ears of corn and seven dry. Yusuf interpreted this as 7 prosperous years followed by 7 years of drought.',
  },
  {
    id: 'ps-049',
    category: 'prophets',
    question: 'What position did Yusuf reach in Egypt?',
    options: { A: 'Commander of the army', B: 'Advisor to the Pharaoh', C: 'Minister/Treasurer in charge of the storehouses', D: 'Judge' },
    correct: 'C',
    explanation: 'After interpreting the King\'s dream, Yusuf was made the treasurer/minister in charge of Egypt\'s storehouses — a position of great trust.',
  },
  {
    id: 'ps-050',
    category: 'prophets',
    question: 'What happened when Yusuf was finally reunited with his family?',
    options: {
      A: 'He punished his brothers for what they did',
      B: 'He forgave his brothers and his father\'s sight was restored when the shirt touched his face',
      C: 'He refused to see them',
      D: 'He moved back to Canaan',
    },
    correct: 'B',
    explanation: 'Yusuf forgave his brothers saying: "No blame on you today." When his shirt was placed on his father Yaqub\'s face, his sight was miraculously restored.',
  },
  {
    id: 'ps-051',
    category: 'prophets',
    question: 'What childhood dream of Yusuf came true in the end?',
    options: { A: 'He became a king', B: 'His brothers, father, and mother bowed to him', C: 'Egypt became Muslim', D: 'He returned to Canaan' },
    correct: 'B',
    explanation: 'When his family arrived in Egypt, they all bowed to him, fulfilling the dream of eleven stars, the sun, and moon bowing to him.',
  },

  // === PROPHET AYYUB (JOB) ===
  {
    id: 'ps-052',
    category: 'prophets',
    question: 'Which prophet is most known in the Quran for his patience in hardship?',
    options: { A: 'Nuh', B: 'Musa', C: 'Ayyub (Job)', D: 'Ibrahim' },
    correct: 'C',
    explanation: 'Ayyub is the exemplar of patience (sabr) in the Quran. He suffered great illness and loss but remained thankful and patient.',
  },
  {
    id: 'ps-053',
    category: 'prophets',
    question: 'How did Allah restore Prophet Ayyub after his suffering?',
    options: { A: 'An angel healed him', B: 'He struck the ground and a spring gushed — he washed and was healed', C: 'He prayed and was healed', D: 'A herb was given to him' },
    correct: 'B',
    explanation: 'Allah told Ayyub: "Strike the ground with your foot; this is a spring to wash in, cool and a (refreshing) drink." (38:42) He was healed and his family restored.',
  },
  {
    id: 'ps-054',
    category: 'prophets',
    question: 'What du\'a did Prophet Ayyub make during his illness?',
    options: {
      A: '"Rabbana atina fid-dunya hasanah"',
      B: '"La ilaha illa anta subhanaka inni kuntu minaz-zalimin"',
      C: '"Anni massaniya ad-durru wa anta arhamur-rahimin"',
      D: '"Rabbana zhalamna anfusana"',
    },
    correct: 'C',
    explanation: 'Ayyub prayed: "Indeed, adversity has touched me, and You are the Most Merciful of all who show mercy." (21:83) Allah answered immediately.',
  },

  // === PROPHET SHU'AYB ===
  {
    id: 'ps-055',
    category: 'prophets',
    question: 'Prophet Shu\'ayb was sent to the people of which city?',
    options: { A: 'Sodom', B: 'Madyan (Midian)', C: 'Babylon', D: 'Nineveh' },
    correct: 'B',
    explanation: 'Shu\'ayb was sent to the people of Madyan, who were known for dishonest trade practices — giving short measure and weight.',
  },
  {
    id: 'ps-056',
    category: 'prophets',
    question: 'What main sin did the people of Madyan commit?',
    options: { A: 'Worshipping idols', B: 'Cheating in weights and measures', C: 'Immoral behaviour', D: 'Killing prophets' },
    correct: 'B',
    explanation: 'The people of Madyan cheated in trade by giving less than the full weight and measure. Shu\'ayb commanded justice in commerce.',
  },

  // === PROPHET MUSA (MOSES) ===
  {
    id: 'ps-057',
    category: 'prophets',
    question: 'Who was Prophet Musa sent to?',
    options: { A: 'The people of \'Ad', B: 'Pharaoh (Fir\'awn) and the Children of Israel', C: 'The Quraysh', D: 'The people of Madyan' },
    correct: 'B',
    explanation: 'Musa was sent primarily to Pharaoh (Fir\'awn) to free the Children of Israel from slavery in Egypt.',
  },
  {
    id: 'ps-058',
    category: 'prophets',
    question: 'Where was baby Musa placed by his mother to save him?',
    options: { A: 'In a cave', B: 'In a basket on the Nile River', C: 'In a well', D: 'With a shepherd' },
    correct: 'B',
    explanation: 'Allah inspired Musa\'s mother to place him in a basket on the Nile to protect him from Pharaoh\'s soldiers who were killing Israelite baby boys.',
  },
  {
    id: 'ps-059',
    category: 'prophets',
    question: 'Who found baby Musa in the basket on the Nile?',
    options: { A: 'Pharaoh\'s soldiers', B: 'Pharaoh\'s wife Asiyah', C: 'An Israelite woman', D: 'His sister' },
    correct: 'B',
    explanation: 'Baby Musa was found and raised in Pharaoh\'s own palace. Pharaoh\'s wife Asiyah convinced Pharaoh to spare the child.',
  },
  {
    id: 'ps-060',
    category: 'prophets',
    question: 'Where did Musa first receive revelation from Allah?',
    options: { A: 'In Egypt', B: 'In Madyan', C: 'At the Valley of Tuwa near a burning bush', D: 'On Mount Sinai during prayer' },
    correct: 'C',
    explanation: 'Musa saw a fire and approached it. Allah called to him from the bush in the sacred valley of Tuwa, giving him his first revelation.',
  },
  {
    id: 'ps-061',
    category: 'prophets',
    question: 'What miracle was given to Prophet Musa involving his staff?',
    options: { A: 'It could bring rain', B: 'It turned into a serpent and parted the sea', C: 'It produced fire', D: 'It healed the sick' },
    correct: 'B',
    explanation: 'Musa\'s staff turned into a serpent that swallowed the magicians\' ropes and staffs. Later, he struck the sea with it and it parted.',
  },
  {
    id: 'ps-062',
    category: 'prophets',
    question: 'What special quality made Musa unique among prophets?',
    options: { A: 'He could fly', B: 'Allah spoke directly to him (Kalimullah)', C: 'He lived the longest', D: 'He had the most followers' },
    correct: 'B',
    explanation: 'Musa is known as Kalimullah (He whom Allah spoke to directly) because Allah spoke to him without any intermediary on Mount Sinai.',
  },
  {
    id: 'ps-063',
    category: 'prophets',
    question: 'What happened to Pharaoh\'s magicians after they witnessed Musa\'s staff become a serpent?',
    options: { A: 'They ran away', B: 'They bowed and declared faith in Allah', C: 'They tried to kill Musa', D: 'They asked Pharaoh to imprison Musa' },
    correct: 'B',
    explanation: 'The magicians immediately prostrated and declared: "We believe in the Lord of Musa and Harun!" They recognised the miracle was beyond human magic.',
  },
  {
    id: 'ps-064',
    category: 'prophets',
    question: 'What happened when Musa parted the Red Sea?',
    options: {
      A: 'The Israelites crossed safely and Pharaoh\'s army drowned',
      B: 'The Israelites drowned',
      C: 'Pharaoh was captured',
      D: 'Both sides crossed safely',
    },
    correct: 'A',
    explanation: 'Allah parted the sea for Musa and the Israelites to cross safely. When Pharaoh and his army followed, the sea closed and they were drowned.',
  },
  {
    id: 'ps-065',
    category: 'prophets',
    question: 'What did Musa receive on Mount Sinai?',
    options: { A: 'The Quran', B: 'The Injeel', C: 'The Tawrat (Torah)', D: 'The Zabur' },
    correct: 'C',
    explanation: 'Musa received the Tawrat (Torah) on Mount Sinai — the scripture and law given to the Children of Israel.',
  },
  {
    id: 'ps-066',
    category: 'prophets',
    question: 'What did the Israelites do while Musa was receiving revelation on Mount Sinai?',
    options: { A: 'They prayed and fasted', B: 'They worshipped a golden calf', C: 'They built a mosque', D: 'They returned to Egypt' },
    correct: 'B',
    explanation: 'The Israelites were led by Samiri to worship a golden calf while Musa was away receiving the Torah. Musa returned furious at his people.',
  },
  {
    id: 'ps-067',
    category: 'prophets',
    question: 'Who was Musa\'s brother and assistant prophet?',
    options: { A: 'Yusuf', B: 'Dawud', C: 'Harun (Aaron)', D: 'Ilyas' },
    correct: 'C',
    explanation: 'Harun (Aaron) was Musa\'s brother. Musa asked Allah to include Harun as a prophet to help him in his mission.',
  },
  {
    id: 'ps-068',
    category: 'prophets',
    question: 'Which man raised Musa in his home after he killed an Egyptian accidentally?',
    options: { A: 'Pharaoh', B: 'Shu\'ayb in Madyan', C: 'Ibrahim', D: 'Yaqub' },
    correct: 'B',
    explanation: 'After fleeing Egypt, Musa went to Madyan and worked for Shu\'ayb for eight to ten years, marrying his daughter.',
  },

  // === PROPHET DAWUD (DAVID) ===
  {
    id: 'ps-069',
    category: 'prophets',
    question: 'Which prophet killed the giant warrior Jalut (Goliath)?',
    options: { A: 'Sulayman', B: 'Musa', C: 'Dawud (David)', D: 'Ibrahim' },
    correct: 'C',
    explanation: 'Young Dawud killed Jalut (Goliath) with a sling while serving in King Talut\'s army. This led to his rise to kingship.',
  },
  {
    id: 'ps-070',
    category: 'prophets',
    question: 'What holy scripture was revealed to Prophet Dawud?',
    options: { A: 'The Torah', B: 'The Injeel', C: 'The Quran', D: 'The Zabur (Psalms)' },
    correct: 'D',
    explanation: 'The Zabur (Psalms) was revealed to Prophet Dawud. He was gifted with an extraordinarily beautiful voice.',
  },
  {
    id: 'ps-071',
    category: 'prophets',
    question: 'What unique ability did Prophet Dawud have with materials?',
    options: { A: 'He could turn lead to gold', B: 'Allah softened iron for him so he could mould it with his hands', C: 'He could shape stone', D: 'He could build with water' },
    correct: 'B',
    explanation: 'Allah softened iron for Dawud, allowing him to mould chain-mail armour without fire or hammers. (Quran 34:10-11)',
  },
  {
    id: 'ps-072',
    category: 'prophets',
    question: 'What did birds and mountains do when Dawud sang praises of Allah?',
    options: { A: 'They listened silently', B: 'They sang praise along with him', C: 'They flew away', D: 'They gathered around him' },
    correct: 'B',
    explanation: 'The Quran says: "We subjected the mountains to glorify (Allah) with him, in the evening and at sunrise, and the birds too, assembling all with him, turning." (38:18-19)',
  },

  // === PROPHET SULAYMAN (SOLOMON) ===
  {
    id: 'ps-073',
    category: 'prophets',
    question: 'Who was the father of Prophet Sulayman?',
    options: { A: 'Musa', B: 'Ibrahim', C: 'Dawud', D: 'Harun' },
    correct: 'C',
    explanation: 'Sulayman (Solomon) was the son of Dawud (David). He inherited his father\'s wisdom and prophethood.',
  },
  {
    id: 'ps-074',
    category: 'prophets',
    question: 'What special ability did Prophet Sulayman have?',
    options: { A: 'He could read minds', B: 'He could speak to and understand animals and birds', C: 'He could become invisible', D: 'He could control fire' },
    correct: 'B',
    explanation: 'Sulayman was given the ability to understand the speech of animals and birds. The Quran records his conversation with an ant and a hoopoe bird.',
  },
  {
    id: 'ps-075',
    category: 'prophets',
    question: 'Which queen visited Prophet Sulayman after hearing about him?',
    options: { A: 'Queen of Egypt', B: 'Queen of Persia', C: 'Queen of Sheba (Bilqis)', D: 'Queen of Rome' },
    correct: 'C',
    explanation: 'The Queen of Sheba (Bilqis) visited Sulayman and accepted Islam after witnessing his wisdom and the miracle of her throne being brought to him.',
  },
  {
    id: 'ps-076',
    category: 'prophets',
    question: 'What creatures were under Sulayman\'s command?',
    options: { A: 'Only animals', B: 'Humans, Jinn, birds, and the wind', C: 'Only the wind', D: 'Angels and Jinn' },
    correct: 'B',
    explanation: 'Allah subjected humans, Jinn, birds, and the wind to Sulayman\'s command. He used Jinn to build great structures.',
  },
  {
    id: 'ps-077',
    category: 'prophets',
    question: 'What bird brought Sulayman news about the Queen of Sheba?',
    options: { A: 'A crow', B: 'An eagle', C: 'A hoopoe (Hudhud)', D: 'A dove' },
    correct: 'C',
    explanation: 'The Hudhud (hoopoe) bird reported to Sulayman about a great queen who ruled her people but worshipped the sun instead of Allah.',
  },
  {
    id: 'ps-078',
    category: 'prophets',
    question: 'What creature warned the others of Sulayman\'s approaching army?',
    options: { A: 'An eagle', B: 'An ant', C: 'A bee', D: 'A horse' },
    correct: 'B',
    explanation: 'An ant warned: "O you ants, go into your dwellings so that Sulayman and his soldiers do not crush you unawares." Sulayman smiled and thanked Allah.',
  },

  // === PROPHET ILYAS & AL-YASA ===
  {
    id: 'ps-079',
    category: 'prophets',
    question: 'Prophet Ilyas (Elijah) called his people away from worshipping which idol?',
    options: { A: 'The golden calf', B: 'Ba\'l', C: 'Hubal', D: 'Lata' },
    correct: 'B',
    explanation: 'Ilyas called the people of his town to abandon the idol Ba\'l and return to worshipping Allah.',
  },
  {
    id: 'ps-080',
    category: 'prophets',
    question: 'Prophet Al-Yasa (Elisha) was the successor of which prophet?',
    options: { A: 'Musa', B: 'Dawud', C: 'Ilyas (Elijah)', D: 'Sulayman' },
    correct: 'C',
    explanation: 'Al-Yasa (Elisha) was the successor and student of Ilyas (Elijah). He continued the mission of guiding the Israelites.',
  },

  // === PROPHET YUNUS (JONAH) ===
  {
    id: 'ps-081',
    category: 'prophets',
    question: 'Which prophet was swallowed by a whale?',
    options: { A: 'Musa', B: 'Ayyub', C: 'Yunus (Jonah)', D: 'Ibrahim' },
    correct: 'C',
    explanation: 'Yunus (Jonah) left his people without permission from Allah, boarded a ship, was thrown overboard, and was swallowed by a large whale.',
  },
  {
    id: 'ps-082',
    category: 'prophets',
    question: 'What du\'a did Yunus make inside the whale?',
    options: {
      A: '"Rabbana atina fid-dunya hasanah"',
      B: '"La ilaha illa anta subhanaka inni kuntu minaz-zalimin"',
      C: '"Hasbunallahu wa ni\'mal wakil"',
      D: '"Rabbi inni lima anzalta ilayya min khayrin faqir"',
    },
    correct: 'B',
    explanation: 'Yunus called out: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers." (21:87) Allah responded and saved him.',
  },
  {
    id: 'ps-083',
    category: 'prophets',
    question: 'To which city was Prophet Yunus sent?',
    options: { A: 'Babylon', B: 'Jerusalem', C: 'Nineveh', D: 'Sodom' },
    correct: 'C',
    explanation: 'Yunus was sent to the people of Nineveh (in modern-day Iraq). When he left prematurely and repented, he returned and his people believed.',
  },
  {
    id: 'ps-084',
    category: 'prophets',
    question: 'What happened to Yunus\'s people while he was in the whale?',
    options: { A: 'They were destroyed', B: 'They repented and believed, so Allah spared them', C: 'They waited for him', D: 'They found a new prophet' },
    correct: 'B',
    explanation: 'When signs of punishment appeared, Yunus\'s people of Nineveh repented sincerely and Allah lifted the punishment from them — a unique event in the Quran.',
  },

  // === PROPHET ZAKARIYYA & YAHYA ===
  {
    id: 'ps-085',
    category: 'prophets',
    question: 'What miracle occurred to Prophet Zakariyya in his old age?',
    options: {
      A: 'He was given a great kingdom',
      B: 'He and his elderly barren wife were given a son — Yahya (John)',
      C: 'He received a new scripture',
      D: 'He was saved from death',
    },
    correct: 'B',
    explanation: 'Zakariyya, old and with a barren wife, prayed for a righteous son. Allah gave him the glad tiding of Yahya (John the Baptist).',
  },
  {
    id: 'ps-086',
    category: 'prophets',
    question: 'Who was the son of Prophet Zakariyya?',
    options: { A: 'Isa (Jesus)', B: 'Musa', C: 'Yahya (John)', D: 'Sulayman' },
    correct: 'C',
    explanation: 'Yahya (John the Baptist) was the son of Zakariyya. The Quran says Yahya confirmed the word of Allah (Isa) and was righteous from childhood.',
  },
  {
    id: 'ps-087',
    category: 'prophets',
    question: 'What sign did Allah give Zakariyya when his prayer was answered?',
    options: { A: 'A bird came to him', B: 'He would not speak to people for three days except by gesture', C: 'A star appeared', D: 'An angel visited him' },
    correct: 'B',
    explanation: 'Allah gave Zakariyya the sign that he would be unable to speak to people for three days despite being healthy, as confirmation of the glad tiding.',
  },

  // === PROPHET MARYAM & ISA (JESUS) ===
  {
    id: 'ps-088',
    category: 'prophets',
    question: 'What is the Islamic belief about the birth of Prophet Isa (Jesus)?',
    options: {
      A: 'He had a normal birth',
      B: 'He was born miraculously to Maryam without a father',
      C: 'He was sent from the sky',
      D: 'He was adopted by Zakariyya',
    },
    correct: 'B',
    explanation: 'Isa was born miraculously to the virgin Maryam (Mary) without a father. Allah said "Be!" and he was. (Quran 3:47)',
  },
  {
    id: 'ps-089',
    category: 'prophets',
    question: 'What miracle did Isa (AS) perform as a newborn?',
    options: { A: 'He walked immediately', B: 'He spoke to the people from the cradle', C: 'He healed his mother', D: 'He called upon Allah' },
    correct: 'B',
    explanation: 'Baby Isa spoke from the cradle, declaring: "Indeed, I am the servant of Allah. He has given me the Scripture and made me a prophet." (19:30)',
  },
  {
    id: 'ps-090',
    category: 'prophets',
    question: 'Which scripture was revealed to Prophet Isa?',
    options: { A: 'The Torah', B: 'The Zabur', C: 'The Quran', D: 'The Injeel (Gospel)' },
    correct: 'D',
    explanation: 'The Injeel (Gospel) was revealed to Prophet Isa (Jesus) as guidance and light.',
  },
  {
    id: 'ps-091',
    category: 'prophets',
    question: 'What did Prophet Isa do to birds made of clay?',
    options: { A: 'He painted them', B: 'He breathed into them and they became alive by Allah\'s permission', C: 'He offered them as charity', D: 'He displayed them in the temple' },
    correct: 'B',
    explanation: 'Among Isa\'s miracles: he fashioned clay birds and breathed into them, and they became living birds by Allah\'s permission. (Quran 3:49)',
  },
  {
    id: 'ps-092',
    category: 'prophets',
    question: 'What is the Islamic belief about the death of Prophet Isa?',
    options: {
      A: 'He was crucified and died',
      B: 'He was not crucified — Allah raised him to the heavens',
      C: 'He died peacefully of old age',
      D: 'He is unknown',
    },
    correct: 'B',
    explanation: 'The Quran states: "They did not kill him, nor did they crucify him... rather, Allah raised him to Himself." (4:157-158)',
  },
  {
    id: 'ps-093',
    category: 'prophets',
    question: 'What miracle did Isa perform for the people of Israel involving food?',
    options: {
      A: 'He multiplied water',
      B: 'He brought down a table spread of food from Heaven (Ma\'idah)',
      C: 'He grew crops instantly',
      D: 'He turned water to juice',
    },
    correct: 'B',
    explanation: 'The disciples asked Isa to pray for a table of food from Heaven (Ma\'idah). Allah sent it down as a sign and feast, and Surah Al-Ma\'idah is named after this event.',
  },
  {
    id: 'ps-094',
    category: 'prophets',
    question: 'What did Isa (AS) heal, by Allah\'s permission?',
    options: { A: 'Only the blind', B: 'The blind and lepers, and he raised the dead', C: 'Only the deaf', D: 'Mental illness only' },
    correct: 'B',
    explanation: 'Among Isa\'s miracles: he healed the blind and lepers, and raised the dead — all by Allah\'s permission. (Quran 3:49)',
  },
  {
    id: 'ps-095',
    category: 'prophets',
    question: 'Which prophet did Isa foretell would come after him?',
    options: { A: 'Dawud', B: 'Yahya', C: 'Muhammad ﷺ', D: 'Ibrahim' },
    correct: 'C',
    explanation: 'Isa said: "...giving good tidings of a messenger to come after me whose name is Ahmad." (61:6) Ahmad is another name of Prophet Muhammad ﷺ.',
  },
  {
    id: 'ps-096',
    category: 'prophets',
    question: 'What is Maryam\'s distinction in the Quran?',
    options: {
      A: 'She is the only woman named in the Quran',
      B: 'She is mentioned more than any other woman and has a chapter named after her',
      C: 'She was the first Muslim woman',
      D: 'She was a prophetess',
    },
    correct: 'B',
    explanation: 'Maryam (Mary) is the only woman named in the Quran and is mentioned more than in the New Testament. Surah Maryam is named after her.',
  },

  // === PROPHET DHUL-KIFL ===
  {
    id: 'ps-097',
    category: 'prophets',
    question: 'Prophet Dhul-Kifl is praised in the Quran for which quality?',
    options: { A: 'His strength', B: 'His patience and righteousness', C: 'His wealth', D: 'His wisdom' },
    correct: 'B',
    explanation: 'The Quran praises Dhul-Kifl alongside Ismail and Idris, describing them all as patient and righteous people. (21:85-86)',
  },

  // === PROPHET MUHAMMAD ﷺ — STORIES ===
  {
    id: 'ps-098',
    category: 'prophets',
    question: 'How old was the Prophet ﷺ when he received his first revelation?',
    options: { A: '25', B: '33', C: '40', D: '50' },
    correct: 'C',
    explanation: 'The Prophet ﷺ received his first revelation at the age of 40, while meditating in the Cave of Hira during Ramadan.',
  },
  {
    id: 'ps-099',
    category: 'prophets',
    question: 'Where did the Prophet\'s ﷺ night journey (Isra) begin?',
    options: { A: 'The Cave of Hira', B: 'The Ka\'bah', C: 'Masjid al-Haram (or his home near it)', D: 'Mount Sinai' },
    correct: 'C',
    explanation: 'The Isra began from Masjid al-Haram in Mecca. The Prophet ﷺ was taken on Buraq to Masjid al-Aqsa in Jerusalem.',
  },
  {
    id: 'ps-100',
    category: 'prophets',
    question: 'What was given to the Prophet ﷺ during the Mi\'raj (ascension to the heavens)?',
    options: { A: 'The Quran was revealed', B: 'The obligation of 5 daily prayers', C: 'The command of Hajj', D: 'Zakat was prescribed' },
    correct: 'B',
    explanation: 'During the Mi\'raj, Allah prescribed 50 prayers initially. Through the Prophet\'s ﷺ conversations (with Moses\'s guidance), it was reduced to 5 while maintaining the reward of 50.',
  },
  {
    id: 'ps-101',
    category: 'prophets',
    question: 'Which of the Prophet\'s ﷺ companions is known as "As-Siddiq" (The Truthful)?',
    options: { A: 'Umar', B: 'Uthman', C: 'Ali', D: 'Abu Bakr' },
    correct: 'D',
    explanation: 'Abu Bakr received the title "As-Siddiq" for immediately believing the Prophet ﷺ when he told of the Isra and Mi\'raj, when others doubted.',
  },
  {
    id: 'ps-102',
    category: 'prophets',
    question: 'What is the name of the cave the Prophet ﷺ and Abu Bakr hid in during the Hijra?',
    options: { A: 'Cave of Hira', B: 'Cave of Thawr', C: 'Cave of Uhud', D: 'Cave of Safa' },
    correct: 'B',
    explanation: 'The Prophet ﷺ and Abu Bakr hid in the Cave of Thawr for three days while the Quraysh searched for them during the Hijra.',
  },
  {
    id: 'ps-103',
    category: 'prophets',
    question: 'What was the first battle fought by the Muslims under the Prophet\'s ﷺ leadership?',
    options: { A: 'Battle of Uhud', B: 'Battle of Khandaq', C: 'Battle of Badr', D: 'Battle of Hunayn' },
    correct: 'C',
    explanation: 'The Battle of Badr in 2 AH (624 CE) was the first major military engagement. 313 Muslims defeated a Meccan army of ~1000.',
  },
  {
    id: 'ps-104',
    category: 'prophets',
    question: 'What was the Treaty of Hudaybiyyah?',
    options: {
      A: 'A war treaty between Muslims and Romans',
      B: 'A peace treaty between the Muslims and Quraysh allowing Muslims to perform Umrah the following year',
      C: 'A trade agreement',
      D: 'A treaty with the Jewish tribes of Madinah',
    },
    correct: 'B',
    explanation: 'The Treaty of Hudaybiyyah (6 AH) was a 10-year peace agreement. Though it appeared unfavourable, Allah called it a clear victory (Quran 48:1).',
  },
  {
    id: 'ps-105',
    category: 'prophets',
    question: 'In which year did the Prophet ﷺ conquer Mecca?',
    options: { A: '5 AH', B: '8 AH', C: '10 AH', D: '2 AH' },
    correct: 'B',
    explanation: 'The conquest of Mecca (Fath Makkah) occurred in 8 AH (630 CE). The Prophet ﷺ entered peacefully and granted amnesty to most of the Meccans.',
  },
  {
    id: 'ps-106',
    category: 'prophets',
    question: 'What did the Prophet ﷺ do when he entered Mecca during the conquest?',
    options: {
      A: 'He punished those who opposed him',
      B: 'He declared: "No blame on you today" and forgave them',
      C: 'He left Mecca immediately',
      D: 'He demolished the Ka\'bah and rebuilt it',
    },
    correct: 'B',
    explanation: 'The Prophet ﷺ forgave the Meccans, saying: "Go — you are all free." He then cleared the Ka\'bah of all idols, declaring "Truth has come and falsehood vanished."',
  },
  {
    id: 'ps-107',
    category: 'prophets',
    question: 'What was the occasion of the last sermon of the Prophet ﷺ?',
    options: { A: 'The conquest of Mecca', B: 'The Farewell Hajj', C: 'The Hijra', D: 'The Battle of Badr' },
    correct: 'B',
    explanation: 'The Prophet ﷺ delivered his Farewell Sermon (Khutbah al-Wada) during his final Hajj in 10 AH, before a large gathering at Mount Arafah.',
  },
  {
    id: 'ps-108',
    category: 'prophets',
    question: 'What did the Prophet ﷺ say at the end of his Farewell Sermon?',
    options: {
      A: '"Make Hajj every year"',
      B: '"Have I conveyed the message? O Allah, bear witness!" — the companions replied yes',
      C: '"Pay your Zakat regularly"',
      D: '"Follow Abu Bakr after me"',
    },
    correct: 'B',
    explanation: 'The Prophet ﷺ asked: "Have I not conveyed the message?" The companions said yes. He said: "O Allah, bear witness!" — completing his mission.',
  },
  {
    id: 'ps-109',
    category: 'prophets',
    question: 'What is the name of the Prophet\'s ﷺ masjid built in Madinah?',
    options: { A: 'Masjid al-Haram', B: 'Masjid al-Aqsa', C: 'Masjid al-Nabawi', D: 'Masjid al-Quba' },
    correct: 'C',
    explanation: 'Masjid al-Nabawi (The Prophet\'s Mosque) in Madinah was built by the Prophet ﷺ himself. It contains his blessed tomb.',
  },
  {
    id: 'ps-110',
    category: 'prophets',
    question: 'What was special about Masjid Quba?',
    options: {
      A: 'It was the largest mosque',
      B: 'It was the first mosque built in Islam (by the Prophet ﷺ upon arriving in Madinah)',
      C: 'It was built by Ibrahim',
      D: 'It is located in Mecca',
    },
    correct: 'B',
    explanation: 'Masjid Quba was the first mosque built in Islam. The Prophet ﷺ said: "Praying two rak\'ahs in Masjid Quba equals the reward of Umrah."',
  },

  // === GENERAL PROPHET FACTS ===
  {
    id: 'ps-111',
    category: 'prophets',
    question: 'How many prophets are believed to have been sent by Allah in total?',
    options: { A: '25', B: '100', C: '124,000 (124 thousand)', D: '1000' },
    correct: 'C',
    explanation: 'According to hadith, approximately 124,000 prophets were sent throughout history. Only 25 are named in the Quran.',
  },
  {
    id: 'ps-112',
    category: 'prophets',
    question: 'Which prophet was swallowed by a fish and whose du\'a became one of the most powerful?',
    options: { A: 'Musa', B: 'Yunus', C: 'Dawud', D: 'Ayyub' },
    correct: 'B',
    explanation: 'Yunus (Jonah) was swallowed by a large fish. His du\'a — "La ilaha illa anta subhanaka inni kuntu minaz-zalimin" — is known as Du\'a al-Yunus.',
  },
  {
    id: 'ps-113',
    category: 'prophets',
    question: 'Which prophet prayed for his community even after they wronged him for 950 years?',
    options: { A: 'Ayyub', B: 'Musa', C: 'Nuh', D: 'Ibrahim' },
    correct: 'C',
    explanation: 'Nuh preached for 950 years. Despite his people\'s rejection, he continued calling them. His final prayer for their destruction came only after Allah\'s revelation to him.',
  },
  {
    id: 'ps-114',
    category: 'prophets',
    question: 'Which prophet is mentioned the most times in the Quran?',
    options: { A: 'Muhammad ﷺ', B: 'Ibrahim', C: 'Musa (Moses)', D: 'Isa' },
    correct: 'C',
    explanation: 'Musa (Moses) is the prophet mentioned most frequently in the Quran, appearing in many chapters and stories.',
  },
  {
    id: 'ps-115',
    category: 'prophets',
    question: 'Which prophet is described as "Ulul Azm" (prophets of strong will and determination)?',
    options: {
      A: 'Adam, Nuh, Ibrahim, Musa, Isa',
      B: 'All 25 prophets',
      C: 'Only Muhammad ﷺ',
      D: 'Nuh, Musa, Dawud, Sulayman, Isa',
    },
    correct: 'A',
    explanation: 'The five prophets of strong will (Ulul Azm) are: Nuh, Ibrahim, Musa, Isa, and Muhammad ﷺ. They are distinguished by their extraordinary patience and resolve.',
  },
  {
    id: 'ps-116',
    category: 'prophets',
    question: 'What is the du\'a Ibrahim ﷺ made that Allah revealed in the Quran about leaving his family in Mecca?',
    options: {
      A: '"Our Lord, accept this from us"',
      B: '"Our Lord, I have settled some of my descendants in an uncultivated valley... so make hearts incline toward them"',
      C: '"Our Lord, grant us patience"',
      D: '"Our Lord, protect this city"',
    },
    correct: 'B',
    explanation: 'Ibrahim prayed: "Our Lord, I have settled some of my descendants in an uncultivated valley near Your sacred House, our Lord, that they may establish prayer. So make hearts among people incline toward them and provide for them from the fruits..." (14:37)',
  },
  {
    id: 'ps-117',
    category: 'prophets',
    question: 'Which prophet asked Allah to show him how He brings the dead back to life?',
    options: { A: 'Musa', B: 'Ibrahim', C: 'Sulayman', D: 'Dawud' },
    correct: 'B',
    explanation: 'Ibrahim asked: "My Lord, show me how You give life to the dead." Allah told him to take four birds, cut them up, put pieces on separate hills, then call them — they returned to life. (2:260)',
  },
  {
    id: 'ps-118',
    category: 'prophets',
    question: 'What did Musa accidentally do in Egypt that caused him to flee?',
    options: { A: 'He preached openly', B: 'He struck an Egyptian man who then died', C: 'He refused to bow to Pharaoh', D: 'He destroyed idols' },
    correct: 'B',
    explanation: 'Musa struck an Egyptian who was fighting an Israelite. The Egyptian died, and Musa fled Egypt out of fear, going to Madyan.',
  },
  {
    id: 'ps-119',
    category: 'prophets',
    question: 'Which wife of Pharaoh is praised in the Quran as a model for the believers?',
    options: { A: 'Hajar', B: 'Asiyah', C: 'Maryam', D: 'Khadijah' },
    correct: 'B',
    explanation: 'Asiyah (Pharaoh\'s wife) is cited in the Quran (66:11) as an example for the believers. She raised Musa and believed in Allah despite being married to the greatest tyrant.',
  },
  {
    id: 'ps-120',
    category: 'prophets',
    question: 'Which prophet was given the wisdom to judge between two women disputing over a child?',
    options: { A: 'Dawud', B: 'Sulayman', C: 'Musa', D: 'Ibrahim' },
    correct: 'B',
    explanation: 'Sulayman cleverly judged between two women both claiming to be a baby\'s mother. His wisdom and judgment is mentioned in Islamic tradition.',
  },
  {
    id: 'ps-121',
    category: 'prophets',
    question: 'What did Prophet Nuh do before entering the Ark?',
    options: { A: 'He prayed for 40 days', B: 'He loaded pairs of every animal as Allah commanded', C: 'He warned people one last time from the ark', D: 'He fasted' },
    correct: 'B',
    explanation: 'Allah commanded Nuh: "Load into the ship two of every kind (male and female)..." (11:40). He boarded with believers and pairs of animals.',
  },
  {
    id: 'ps-122',
    category: 'prophets',
    question: 'Yusuf said "Indeed, it is my Lord who is subtle in fulfilling what He wills." What does this tell us about his character?',
    options: { A: 'He was ungrateful', B: 'He attributed all good to Allah and remained humble', C: 'He was boastful', D: 'He was resigned to fate' },
    correct: 'B',
    explanation: 'Yusuf consistently attributed his success and survival to Allah\'s plan, not his own doing. His life is a lesson in patience and trust in Allah (tawakkul).',
  },
  {
    id: 'ps-123',
    category: 'prophets',
    question: 'What was the name of the Pharaoh\'s chief magician who led the magicians against Musa?',
    options: { A: 'Samiri', B: 'Haman', C: 'The Quran does not name them', D: 'Qarun' },
    correct: 'C',
    explanation: 'The Quran does not name Pharaoh\'s magicians. After witnessing Musa\'s miracle, they all prostrated and declared faith, accepting whatever punishment Pharaoh threatened.',
  },
  {
    id: 'ps-124',
    category: 'prophets',
    question: 'Who was Qarun (Korah) and what happened to him?',
    options: {
      A: 'A prophet who was rewarded with wealth',
      B: 'A man from Musa\'s people who had great wealth but was arrogant — he was swallowed by the earth',
      C: 'A Pharaoh\'s general who drowned',
      D: 'A companion of the Prophet ﷺ',
    },
    correct: 'B',
    explanation: 'Qarun was from Musa\'s people — given great treasure but became arrogant, claiming his wealth was by his own merit. Allah caused the earth to swallow him and his home. (28:76-82)',
  },
  {
    id: 'ps-125',
    category: 'prophets',
    question: 'What was unique about how Sulayman\'s throne room was built?',
    options: { A: 'Angels built it', B: 'Jinn were commanded to build great structures for him', C: 'It was built of solid gold', D: 'It was built on water' },
    correct: 'B',
    explanation: 'Allah subjected the Jinn to Sulayman, and they built great palaces, temples, and structures. Sulayman directed them in mighty works. (34:12-13)',
  },
  {
    id: 'ps-126',
    category: 'prophets',
    question: 'What lesson does the story of Yusuf (AS) teach believers?',
    options: {
      A: 'Wealth leads to happiness',
      B: 'Hardship can lead to great elevation — patience and trust in Allah always leads to good',
      C: 'Family always betrays you',
      D: 'Politics is the path to success',
    },
    correct: 'B',
    explanation: 'Yusuf\'s story — from the well to prison to becoming a minister — teaches that Allah\'s plan is perfect. Patience (sabr) and trust in Allah (tawakkul) always lead to relief.',
  },
  {
    id: 'ps-127',
    category: 'prophets',
    question: 'What did the Prophet ﷺ say about the story of Yusuf?',
    options: { A: 'It is the saddest story', B: 'It is the best of stories (ahsan al-qasas)', C: 'It is the longest story', D: 'It is the most complex' },
    correct: 'B',
    explanation: 'Allah says at the beginning of Surah Yusuf: "We relate to you the best of stories..." (12:3). It is the most complete narrative in the Quran.',
  },
  {
    id: 'ps-128',
    category: 'prophets',
    question: 'Which prophet is called "Abul Anbiya\'" (Father of the Prophets)?',
    options: { A: 'Adam', B: 'Nuh', C: 'Musa', D: 'Ibrahim' },
    correct: 'D',
    explanation: 'Ibrahim is called Abul Anbiya\' (Father of the Prophets) because many prophets descended from his two sons, Ismail and Ishaq.',
  },
  {
    id: 'ps-129',
    category: 'prophets',
    question: 'What happened to Prophet Ibrahim\'s father after he was called to Islam?',
    options: {
      A: 'He accepted Islam',
      B: 'He died as an unbeliever — Ibrahim was forbidden from praying for him',
      C: 'He was punished immediately',
      D: 'He became a king',
    },
    correct: 'B',
    explanation: 'Ibrahim\'s father (Azar) rejected Islam and died as an unbeliever. Ibrahim had prayed for his forgiveness, but was told not to seek forgiveness for the mushrikeen (9:114).',
  },
  {
    id: 'ps-130',
    category: 'prophets',
    question: 'Which prophet had 12 sons who became the ancestors of the 12 tribes of Israel?',
    options: { A: 'Ibrahim', B: 'Ishaq', C: 'Yaqub (Jacob)', D: 'Yusuf' },
    correct: 'C',
    explanation: 'Yaqub (Jacob/Israel) had 12 sons including Yusuf and Binyamin (Benjamin). The 12 tribes of Israel are named after his 12 sons.',
  },
  {
    id: 'ps-131',
    category: 'prophets',
    question: 'What was Ayyub\'s (AS) most praised quality according to the Quran?',
    options: { A: 'His strength', B: 'His patience (Sabr)', C: 'His wealth', D: 'His wisdom' },
    correct: 'B',
    explanation: 'The Quran praises Ayyub: "Indeed, We found him patient, an excellent servant. Indeed, he was one repeatedly turning back (to Allah)." (38:44)',
  },
  {
    id: 'ps-132',
    category: 'prophets',
    question: 'According to Islamic tradition, where is Prophet Musa buried?',
    options: { A: 'Egypt', B: 'Jerusalem', C: 'Near the holy land — the Prophet ﷺ said he saw him on the night of Mi\'raj', D: 'Mount Sinai' },
    correct: 'C',
    explanation: 'The Prophet ﷺ passed by a man praying in his grave on the night of Mi\'raj, identified as Musa. Musa is said to be buried near a red sand dune close to the holy land.',
  },
  {
    id: 'ps-133',
    category: 'prophets',
    question: 'What title is given to Musa for being granted direct speech with Allah?',
    options: { A: 'Khalilullah', B: 'Kalimullah', C: 'Habibullah', D: 'Ruhullah' },
    correct: 'B',
    explanation: 'Musa is known as Kalimullah (He to whom Allah spoke directly). Allah spoke to him directly on Mount Sinai without any intermediary.',
  },
  {
    id: 'ps-134',
    category: 'prophets',
    question: 'Which prophet\'s wife was Asiyah — described as a model for believers?',
    options: { A: 'Musa', B: 'Ibrahim', C: 'Pharaoh (Fir\'awn) — but she believed in Allah', D: 'Yunus' },
    correct: 'C',
    explanation: 'Asiyah was the wife of Pharaoh (Fir\'awn) but she believed in Allah and raised baby Musa. The Quran holds her up as an example for the believers (66:11).',
  },
  {
    id: 'ps-135',
    category: 'prophets',
    question: 'The Quran says "Verily, with hardship comes ease." Which prophet\'s story best illustrates this theme?',
    options: { A: 'Nuh', B: 'Yusuf', C: 'Ibrahim', D: 'All of the above — every prophet experienced this' },
    correct: 'D',
    explanation: 'Every prophet experienced hardship before relief. Nuh faced 950 years of rejection; Ibrahim was thrown in fire; Yusuf was in a well and prison. Allah\'s promise of ease after hardship is universal.',
  },
  {
    id: 'ps-136',
    category: 'prophets',
    question: 'What miracle was Sulayman (AS) given regarding the wind?',
    options: { A: 'He could stop storms', B: 'The wind was subjected to carry him and his army at his command', C: 'He could predict weather', D: 'He could create wind' },
    correct: 'B',
    explanation: 'Allah says: "And to Sulayman (We subjected) the wind, blowing forcefully, proceeding by his command toward the land which We had blessed." (21:81)',
  },
  {
    id: 'ps-137',
    category: 'prophets',
    question: 'Which prophet spent 40 nights on a mountain receiving divine communication?',
    options: { A: 'Ibrahim', B: 'Dawud', C: 'Musa', D: 'Sulayman' },
    correct: 'C',
    explanation: 'Musa spent 40 nights on Mount Sinai (Tur Sinai) in the presence of Allah, receiving the Torah and other commands.',
  },
  {
    id: 'ps-138',
    category: 'prophets',
    question: 'The story of which prophet warns against arrogance and teaches that power comes only from Allah?',
    options: { A: 'Yunus', B: 'Namrud vs Ibrahim', C: 'Pharaoh vs Musa', D: 'Both B and C' },
    correct: 'D',
    explanation: 'Both Namrud (who debated Ibrahim) and Pharaoh (who opposed Musa) claimed divine power. Both were destroyed, showing that arrogance against Allah ends in ruin.',
  },
  {
    id: 'ps-139',
    category: 'prophets',
    question: 'What did Dawud (AS) use to kill Jalut (Goliath)?',
    options: { A: 'A sword', B: 'An arrow', C: 'A stone from a sling', D: 'A spear' },
    correct: 'C',
    explanation: 'Dawud struck Jalut with a stone from his sling. This act of faith — a young man defeating a mighty warrior — led to Dawud\'s rise as king.',
  },
  {
    id: 'ps-140',
    category: 'prophets',
    question: 'What did Yahya (John the Baptist) do that distinguished him from birth?',
    options: {
      A: 'He was born speaking',
      B: 'He was given wisdom as a child and was pure and devout from youth',
      C: 'He performed miracles as a child',
      D: 'He memorised the Torah at age 3',
    },
    correct: 'B',
    explanation: 'The Quran says: "O Yahya, take the Scripture with determination." And We gave him wisdom while yet a child." (19:12) He was pious and devout from his youth.',
  },
  {
    id: 'ps-141',
    category: 'prophets',
    question: 'Which prophet made a du\'a from the belly of a whale that Muslims still recite today?',
    options: { A: 'Musa', B: 'Ibrahim', C: 'Yunus', D: 'Ayyub' },
    correct: 'C',
    explanation: 'Yunus\'s du\'a from the whale — "La ilaha illa anta subhanaka inni kuntu minaz-zalimin" — is recited by Muslims in distress. The Prophet ﷺ said it has never failed to bring relief.',
  },
  {
    id: 'ps-142',
    category: 'prophets',
    question: 'The fire Ibrahim was thrown into became cool and safe. What does this teach?',
    options: {
      A: 'Fire is not dangerous',
      B: 'Allah\'s power supersedes all natural laws — nothing can harm the believer if Allah protects them',
      C: 'Ibrahim was made of special material',
      D: 'The people were wrong to make fire',
    },
    correct: 'B',
    explanation: 'Ibrahim\'s miracle in the fire shows that natural laws operate by Allah\'s command. When He decrees something safe, nothing in creation can cause harm.',
  },
  {
    id: 'ps-143',
    category: 'prophets',
    question: 'Which prophet\'s story involves the "People of the Cave" (Ashabul Kahf)?',
    options: { A: 'The story predates the prophets', B: 'It occurred during the time of Isa', C: 'It is mentioned in Surah Al-Kahf but not linked to a specific prophet', D: 'It is about Musa\'s companions' },
    correct: 'C',
    explanation: 'The story of the Companions of the Cave (Ashabul Kahf) is told in Surah Al-Kahf (Chapter 18). They were believing youth who fled persecution and slept for over 300 years.',
  },
  {
    id: 'ps-144',
    category: 'prophets',
    question: 'What characteristic do all prophets share according to Islamic belief?',
    options: {
      A: 'They were all kings',
      B: 'They were all sinless in conveying the message and had the highest moral character',
      C: 'They all had the same miracles',
      D: 'They all came from the same family',
    },
    correct: 'B',
    explanation: 'All prophets were truthful (sadiq), trustworthy (amin), they conveyed the message (tabligh), and were free of major sin in their prophetic role. They all had the highest moral character.',
  },
  {
    id: 'ps-145',
    category: 'prophets',
    question: 'Which prophet had his sight restored by his son\'s shirt?',
    options: { A: 'Ibrahim', B: 'Yaqub', C: 'Ishaq', D: 'Nuh' },
    correct: 'B',
    explanation: 'Yaqub had lost his sight weeping for Yusuf. When Yusuf\'s shirt was placed on his face in Egypt, his sight was miraculously restored.',
  },
  {
    id: 'ps-146',
    category: 'prophets',
    question: 'Which prophet led thousands but they all died at once — and then he prayed and they were brought back to life?',
    options: { A: 'Musa', B: 'Sulayman', C: 'Khidr', D: 'The story is of the thousands who fled Musa\'s company — Quran 2:243' },
    correct: 'D',
    explanation: 'The Quran mentions thousands who fled fearing death. Allah caused them to die, then brought them back to life. "Have you not considered those who left their homes in the thousands, fearing death?" (2:243)',
  },
  {
    id: 'ps-147',
    category: 'prophets',
    question: 'What did Musa do when he saw his staff had become a snake?',
    options: { A: 'He picked it up immediately', B: 'He was afraid and ran away, but Allah told him to take it and not fear', C: 'He praised Allah', D: 'He threw it into the sea' },
    correct: 'B',
    explanation: 'Musa fled from it in fear. Allah said: "Take it and do not fear; We will return it to its former condition." (20:21) This showed human nature even in prophets.',
  },
  {
    id: 'ps-148',
    category: 'prophets',
    question: 'Which prophet is described as being raised high in the Quran and whose exact status is debated?',
    options: { A: 'Khidr', B: 'Idris', C: 'Dhul-Kifl', D: 'Al-Yasa' },
    correct: 'B',
    explanation: 'The Quran says of Idris: "And We raised him to a high station." (19:57) Some scholars say he was raised alive to the heavens, similar to Isa.',
  },
  {
    id: 'ps-149',
    category: 'prophets',
    question: 'What does the life of all prophets teach us collectively?',
    options: {
      A: 'That life will always be easy for the righteous',
      B: 'That Allah tests those He loves most — prophets suffered greatly but their trust in Allah never wavered',
      C: 'That you need political power to spread truth',
      D: 'That miracles are the only way to convince people',
    },
    correct: 'B',
    explanation: 'Every prophet faced rejection, hardship, and trials — yet their trust in Allah (tawakkul) and patience (sabr) never wavered. The Prophet ﷺ said: "The greatest reward is with the greatest trial."',
  },
  {
    id: 'ps-150',
    category: 'prophets',
    question: 'What is the du\'a Musa made when he arrived in Madyan, tired and hungry?',
    options: {
      A: '"Rabbi inni lima anzalta ilayya min khayrin faqir" (My Lord, I am in need of whatever good You send down to me)',
      B: '"Rabbana atina fid-dunya hasanah"',
      C: '"La ilaha illa anta subhanaka"',
      D: '"Rabbi zidni ilma"',
    },
    correct: 'A',
    explanation: 'After helping the women water their flocks, Musa sat in the shade and made this heartfelt du\'a: "My Lord, indeed I am in need of whatever good You would send down to me." (28:24) Shortly after, he was provided food and shelter.',
  },
]
