import type { QuizQuestion } from '@/types/musabaqah'

// Section 1: Qur'an-Based Questions (25)
// Correct answer distribution: A=7, B=6, C=6, D=6

export const QURAN_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q-001',
    category: 'quran',
    question: 'Which concept explains why some Qur\'anic verses require contextual understanding?',
    options: { A: 'Asbab al-Nuzul', B: 'Tajweed', C: 'Qira\'at', D: 'Ijaz' },
    correct: 'A',
    explanation: 'Asbab al-Nuzul (occasions/reasons of revelation) provides the historical context in which verses were revealed, which is essential for correct interpretation.',
  },
  {
    id: 'q-002',
    category: 'quran',
    question: 'What is the primary purpose of Makki revelations?',
    options: { A: 'Legal rulings', B: 'Strengthening faith and monotheism', C: 'Social contracts', D: 'Inheritance laws' },
    correct: 'B',
    explanation: 'Makki surahs were revealed before the Hijrah and focused on establishing Tawhid (monotheism) and strengthening the faith of the early Muslim community.',
  },
  {
    id: 'q-003',
    category: 'quran',
    question: 'Which Surah emphasizes accountability even for intentions?',
    options: { A: 'Al-Asr', B: 'Al-Baqarah', C: 'Al-Ikhlas', D: 'Al-Zalzalah' },
    correct: 'D',
    explanation: 'Surah Al-Zalzalah (99) states that whoever does an atom\'s weight of good or evil will see it — a powerful reminder that even the smallest intention and deed is recorded.',
  },
  {
    id: 'q-004',
    category: 'quran',
    question: 'The Qur\'an frequently pairs belief (Iman) with which action?',
    options: { A: 'Righteous deeds', B: 'Knowledge', C: 'Wealth', D: 'Leadership' },
    correct: 'A',
    explanation: 'Throughout the Qur\'an, "those who believe and do righteous deeds" appears repeatedly, showing that true faith must be accompanied by action.',
  },
  {
    id: 'q-005',
    category: 'quran',
    question: 'Which Qur\'anic theme appears most consistently across all periods of revelation?',
    options: { A: 'Warfare', B: 'Monotheism (Tawhid)', C: 'Inheritance', D: 'Migration' },
    correct: 'B',
    explanation: 'Tawhid — the absolute oneness of Allah — is the central and consistent theme of the entire Qur\'an, from the earliest Makki surahs to the latest Madani revelations.',
  },
  {
    id: 'q-006',
    category: 'quran',
    question: 'Which Arabic term refers to Qur\'anic verses with clear, unambiguous meaning?',
    options: { A: 'Mutashabihat', B: 'Nasikh', C: 'Qira\'at', D: 'Muhkamat' },
    correct: 'D',
    explanation: 'Muhkamat are the clear, firmly established verses that form the foundation of the Qur\'an\'s legislation and belief. They stand in contrast to the Mutashabihat (allegorical verses).',
  },
  {
    id: 'q-007',
    category: 'quran',
    question: 'The Qur\'an describes itself primarily as what?',
    options: { A: 'A history book', B: 'Guidance for humanity', C: 'A scientific manual', D: 'Legal constitution' },
    correct: 'B',
    explanation: 'The Qur\'an opens with "a guidance for the God-fearing" (Al-Baqarah 2:2) and repeatedly describes itself as Huda — guidance for all of humanity.',
  },
  {
    id: 'q-008',
    category: 'quran',
    question: 'Which Surah was revealed entirely in Madinah?',
    options: { A: 'Al-Baqarah', B: 'Al-Ikhlas', C: 'Al-Mutaffifin', D: 'Al-Alaq' },
    correct: 'A',
    explanation: 'Surah Al-Baqarah is the longest Surah in the Qur\'an and is entirely Madani, covering topics from law to faith to Qiblah change after the Hijrah.',
  },
  {
    id: 'q-009',
    category: 'quran',
    question: 'The Qur\'an discourages blind following of what?',
    options: { A: 'Scholars', B: 'Truth', C: 'Parents', D: 'Revelation' },
    correct: 'C',
    explanation: 'The Qur\'an criticises those who blindly follow the ways of their forefathers, even when those customs contradict divine guidance (Al-Baqarah 2:170).',
  },
  {
    id: 'q-010',
    category: 'quran',
    question: 'Which concept explains the abrogation of certain Qur\'anic rulings?',
    options: { A: 'Tafsir', B: 'Tajweed', C: 'Ijaz', D: 'Nasikh wa Mansukh' },
    correct: 'D',
    explanation: 'Nasikh wa Mansukh (the abrogating and the abrogated) refers to the process by which certain earlier rulings were superseded by later revelations — a gradual divine legislative method.',
  },
  {
    id: 'q-011',
    category: 'quran',
    question: 'The Qur\'an addresses humans and jinn collectively to emphasize:',
    options: { A: 'Superiority', B: 'Fear', C: 'Accountability', D: 'Wealth' },
    correct: 'C',
    explanation: 'In Surah Al-Rahman, Allah addresses both humans and jinn repeatedly to remind them of His blessings and that all creation will be held accountable before Him.',
  },
  {
    id: 'q-012',
    category: 'quran',
    question: 'Which Surah highlights social justice and fair trade?',
    options: { A: 'Al-Mutaffifin', B: 'Al-Fil', C: 'Al-Qadr', D: 'Al-Falaq' },
    correct: 'A',
    explanation: 'Surah Al-Mutaffifin (83) opens with a stern warning against those who defraud others in weights and measures, making it one of the strongest Qur\'anic statements on economic justice.',
  },
  {
    id: 'q-013',
    category: 'quran',
    question: 'The Qur\'an was revealed gradually primarily to:',
    options: { A: 'Reduce memorisation', B: 'Ease understanding and application', C: 'Increase its length', D: 'Test scholars' },
    correct: 'B',
    explanation: 'Allah revealed the Qur\'an over 23 years so people could absorb and apply its teachings step by step — as stated in Al-Furqan 25:32, "We have revealed it in stages."',
  },
  {
    id: 'q-014',
    category: 'quran',
    question: 'Which theme dominates Surah Yusuf?',
    options: { A: 'War strategy', B: 'Economic law', C: 'Patience and divine planning', D: 'Inheritance' },
    correct: 'C',
    explanation: 'Surah Yusuf (12) is described as "the best of stories" and throughout it, Prophet Yusuf\'s patience and trust in Allah\'s plan are the overarching lessons.',
  },
  {
    id: 'q-015',
    category: 'quran',
    question: 'The Qur\'an repeatedly warns against which inner disease?',
    options: { A: 'Poverty', B: 'Forgetfulness', C: 'Illiteracy', D: 'Hypocrisy' },
    correct: 'D',
    explanation: 'The Qur\'an devotes extensive passages (e.g. Al-Baqarah 2:8–20; Al-Munafiqun) to exposing the spiritual disease of hypocrisy (nifaq) as one of the gravest dangers.',
  },
  {
    id: 'q-016',
    category: 'quran',
    question: 'Which Qur\'anic concept balances hope and fear in a believer\'s heart?',
    options: { A: 'Tawakkul', B: 'Taqwa', C: 'Shirk', D: 'Ilm' },
    correct: 'B',
    explanation: 'Taqwa (God-consciousness) creates the perfect balance — a believer fears Allah\'s punishment enough to avoid sin, while maintaining hope in His mercy and striving to please Him.',
  },
  {
    id: 'q-017',
    category: 'quran',
    question: 'The Qur\'an criticises excessive questioning when it leads to:',
    options: { A: 'Hardship', B: 'Knowledge', C: 'Guidance', D: 'Wisdom' },
    correct: 'A',
    explanation: 'The Qur\'an warns in Al-Maidah 5:101 that asking unnecessary questions about divine rulings can make obligations harder for you — as happened with the people of Musa when they questioned the cow.',
  },
  {
    id: 'q-018',
    category: 'quran',
    question: 'Which Surah focuses heavily on ethical conduct between Muslims?',
    options: { A: 'Al-Masad', B: 'Al-Qariah', C: 'Al-Hujurat', D: 'Al-Nas' },
    correct: 'C',
    explanation: 'Surah Al-Hujurat (49) is often called the "social manners" surah — it prohibits mockery, suspicion, backbiting, and commands verification of news and reconciliation between believers.',
  },
  {
    id: 'q-019',
    category: 'quran',
    question: 'The Qur\'an describes worldly life (dunya) as:',
    options: { A: 'Permanent', B: 'Worthless', C: 'Punishment', D: 'Illusionary enjoyment' },
    correct: 'D',
    explanation: 'The Qur\'an consistently describes the dunya as "mata\' al-ghurur" — the enjoyment of deception (Al-Imran 3:185). It is temporary and distracting from what truly matters.',
  },
  {
    id: 'q-020',
    category: 'quran',
    question: 'Which Islamic legal principle ensures ease in rulings during hardship?',
    options: { A: 'Removal of difficulty', B: 'Rigidity', C: 'Hardship', D: 'Strictness' },
    correct: 'A',
    explanation: 'The Qur\'an states "Allah intends ease for you and does not intend hardship" (Al-Baqarah 2:185). This is one of the five universal objectives (Maqasid) of Shariah.',
  },
  {
    id: 'q-021',
    category: 'quran',
    question: 'Which Surah calls upon time itself as a witness to human loss?',
    options: { A: 'Al-Balad', B: 'Al-Inshirah', C: 'Al-Asr', D: 'Al-Takathur' },
    correct: 'C',
    explanation: 'Surah Al-Asr (103) opens with an oath by time and declares that all humans are in loss — except those who believe, do good, and mutually enjoin truth and patience.',
  },
  {
    id: 'q-022',
    category: 'quran',
    question: 'Which Qur\'anic value governs speech ethics?',
    options: { A: 'Silence', B: 'Truthfulness and wisdom', C: 'Argument', D: 'Debate' },
    correct: 'B',
    explanation: 'The Qur\'an commands speaking truthfully (qawlan sadidan, Al-Ahzab 33:70), wisely (qawlan hakiman), and gently — speech is considered an act of worship or sin depending on its nature.',
  },
  {
    id: 'q-023',
    category: 'quran',
    question: 'The Qur\'an condemns arrogance by referencing which figures?',
    options: { A: 'Pharaoh only', B: 'Qarun only', C: 'Iblis only', D: 'All of the above' },
    correct: 'D',
    explanation: 'Pharaoh (arrogance toward people), Qarun (arrogance through wealth), and Iblis (arrogance toward Allah\'s command) are all cited in the Qur\'an as cautionary examples of arrogance.',
  },
  {
    id: 'q-024',
    category: 'quran',
    question: 'Which Surah highlights divine mercy most prominently?',
    options: { A: 'Al-Kafirun', B: 'Al-Quraish', C: 'Al-Rahman', D: 'Al-Humazah' },
    correct: 'C',
    explanation: 'Surah Al-Rahman (55) repeats "Which of the favours of your Lord would you deny?" 31 times, making it a sustained declaration of Allah\'s mercy and generosity toward creation.',
  },
  {
    id: 'q-025',
    category: 'quran',
    question: 'Which Qur\'anic command promotes verification of news before acting on it?',
    options: { A: 'Verification before judgment', B: 'Charity', C: 'Justice', D: 'Migration' },
    correct: 'A',
    explanation: 'Al-Hujurat 49:6 commands believers to verify news from a corrupt person before acting on it, lest they harm people in ignorance — a cornerstone of Islamic media ethics.',
  },
]
