import type { QuizQuestion } from '@/types/musabaqah'

// Section 2: Hadith-Based Questions (25)
// Correct answer distribution: A=6, B=6, C=7, D=6

export const SUNNAH_QUESTIONS: QuizQuestion[] = [
  {
    id: 'sn-001',
    category: 'sunnah',
    question: 'According to the hadith "Actions are judged by intentions," what determines reward?',
    options: { A: 'Difficulty', B: 'Visibility', C: 'The intention behind the action', D: 'Speed' },
    correct: 'C',
    explanation: 'The Prophet ﷺ said "Actions are by intentions, and every person gets what they intended." (Bukhari, Muslim) — making niyyah the foundation of all worship.',
  },
  {
    id: 'sn-002',
    category: 'sunnah',
    question: 'Which deed is described as Sadaqah Jariyah — a continuous flowing charity?',
    options: { A: 'Knowledge that benefits others', B: 'Fasting', C: 'Hajj', D: 'Prayer' },
    correct: 'A',
    explanation: 'The Prophet ﷺ said: "When a person dies, their deeds end except three: continuous charity, beneficial knowledge, and a righteous child who prays for them." (Muslim)',
  },
  {
    id: 'sn-003',
    category: 'sunnah',
    question: 'The Prophet ﷺ emphasised moderation primarily in which area?',
    options: { A: 'Wealth', B: 'Speech', C: 'Trade', D: 'Worship' },
    correct: 'D',
    explanation: 'The Prophet ﷺ warned against extremism in worship, saying: "Take up good deeds only as much as you are able." Consistent moderate acts are more beloved than intense but unsustainable ones.',
  },
  {
    id: 'sn-004',
    category: 'sunnah',
    question: 'Which behavior does the hadith say nullifies good character?',
    options: { A: 'Silence', B: 'Arrogance', C: 'Patience', D: 'Humility' },
    correct: 'B',
    explanation: 'The Prophet ﷺ said: "No one who has even a mustard seed\'s weight of arrogance in his heart will enter Paradise." (Muslim) — arrogance destroys the virtue of good character.',
  },
  {
    id: 'sn-005',
    category: 'sunnah',
    question: 'Which quality completes a believer\'s faith according to the famous hadith?',
    options: { A: 'Strength', B: 'Intelligence', C: 'Loving for others what one loves for oneself', D: 'Wealth' },
    correct: 'C',
    explanation: 'The Prophet ﷺ said: "None of you truly believes until he loves for his brother what he loves for himself." (Bukhari, Muslim) — a foundational principle of Islamic brotherhood.',
  },
  {
    id: 'sn-006',
    category: 'sunnah',
    question: 'The most beloved deeds to Allah are those that are:',
    options: { A: 'Difficult', B: 'Public', C: 'Short', D: 'Consistent' },
    correct: 'D',
    explanation: 'The Prophet ﷺ said: "The most beloved deed to Allah is the most consistent one, even if it is small." (Bukhari, Muslim) — consistency matters more than intensity.',
  },
  {
    id: 'sn-007',
    category: 'sunnah',
    question: 'What action weighs most heavily on the scale on the Day of Judgement?',
    options: { A: 'Good character', B: 'Silence', C: 'Travel', D: 'Debate' },
    correct: 'A',
    explanation: 'The Prophet ﷺ said: "Nothing will be heavier on the believer\'s scale on the Day of Resurrection than good character." (Abu Dawud, Tirmidhi)',
  },
  {
    id: 'sn-008',
    category: 'sunnah',
    question: 'Which sin is most associated with the heart and intentions rather than outward actions?',
    options: { A: 'Theft', B: 'Hypocrisy', C: 'Murder', D: 'Gambling' },
    correct: 'B',
    explanation: 'Hypocrisy (nifaq) is a sin of the heart — saying one thing and believing another. The Prophet ﷺ described its signs: lying, breaking promises, and betraying trust.',
  },
  {
    id: 'sn-009',
    category: 'sunnah',
    question: 'Which group receives shade on the Day of Judgement when there is no other shade?',
    options: { A: 'Wealthy traders', B: 'Poets', C: 'Travelers', D: 'Just leaders' },
    correct: 'D',
    explanation: 'One of the seven groups the Prophet ﷺ mentioned who receive Allah\'s shade is "a just leader." Justice in authority is one of the highest forms of worship in Islam.',
  },
  {
    id: 'sn-010',
    category: 'sunnah',
    question: 'Seeking knowledge in Islam is considered:',
    options: { A: 'Optional', B: 'Cultural', C: 'Obligatory', D: 'Seasonal' },
    correct: 'C',
    explanation: 'The Prophet ﷺ said: "Seeking knowledge is an obligation upon every Muslim." (Ibn Majah) — acquiring the knowledge needed to worship Allah correctly is a religious duty.',
  },
  {
    id: 'sn-011',
    category: 'sunnah',
    question: 'Which habit does the hadith say protects a person from regret?',
    options: { A: 'Reflection before speaking', B: 'Silence', C: 'Wealth', D: 'Travel' },
    correct: 'A',
    explanation: 'The Prophet ﷺ said: "Whoever believes in Allah and the Last Day should speak good or remain silent." (Bukhari, Muslim) — thinking before speaking prevents regret.',
  },
  {
    id: 'sn-012',
    category: 'sunnah',
    question: 'Which trait did the Prophet ﷺ warn against most strongly?',
    options: { A: 'Poverty', B: 'Simplicity', C: 'Humility', D: 'Arrogance' },
    correct: 'D',
    explanation: 'Arrogance is condemned across multiple hadith. The Prophet ﷺ defined it as "rejecting truth and looking down on people" — the very sin that caused the downfall of Iblis.',
  },
  {
    id: 'sn-013',
    category: 'sunnah',
    question: 'Which act erases minor sins according to authentic hadith?',
    options: { A: 'Trade', B: 'Patience', C: 'Ablution performed properly', D: 'Silence' },
    correct: 'C',
    explanation: 'The Prophet ﷺ said that when a Muslim performs wudu properly, their sins fall away with every drop of water until they emerge purified. (Muslim)',
  },
  {
    id: 'sn-014',
    category: 'sunnah',
    question: 'Which deed continues to benefit a person even after their death?',
    options: { A: 'Prayer', B: 'Knowledge taught', C: 'Charity', D: 'Travel' },
    correct: 'B',
    explanation: 'Among the three acts that continue after death, "beneficial knowledge" means knowledge someone shared or wrote that others continue to use and benefit from.',
  },
  {
    id: 'sn-015',
    category: 'sunnah',
    question: 'Which trait most defines a true believer according to the hadith on trustworthiness?',
    options: { A: 'Trustworthiness', B: 'Intelligence', C: 'Strength', D: 'Wealth' },
    correct: 'A',
    explanation: 'The Prophet ﷺ said: "There is no faith for one who has no trustworthiness (amanah)." (Ahmad) — trustworthiness is the foundation of Islamic character.',
  },
  {
    id: 'sn-016',
    category: 'sunnah',
    question: 'Which behavior breaks the bond of brotherhood between Muslims?',
    options: { A: 'Advice', B: 'Forgiveness', C: 'Suspicion', D: 'Charity' },
    correct: 'C',
    explanation: 'The Prophet ﷺ said: "Beware of suspicion, for suspicion is the worst form of lying." (Bukhari) — unfounded negative assumptions destroy trust between believers.',
  },
  {
    id: 'sn-017',
    category: 'sunnah',
    question: 'Which quality leads to Allah\'s love, according to the hadith on mercy?',
    options: { A: 'Pride', B: 'Mercy', C: 'Argument', D: 'Silence' },
    correct: 'B',
    explanation: 'The Prophet ﷺ said: "The merciful will be shown mercy by the Most Merciful. Be merciful to those on earth, and the One in the heavens will have mercy on you." (Abu Dawud, Tirmidhi)',
  },
  {
    id: 'sn-018',
    category: 'sunnah',
    question: 'Which sin of the tongue is explicitly mentioned in the hadith as a major danger?',
    options: { A: 'Envy', B: 'Greed', C: 'Laziness', D: 'Backbiting' },
    correct: 'D',
    explanation: 'The Prophet ﷺ defined backbiting as mentioning your brother in a way he would dislike. It is described in the Qur\'an as eating the flesh of your dead brother (Al-Hujurat 49:12).',
  },
  {
    id: 'sn-019',
    category: 'sunnah',
    question: 'Which practice does the hadith say increases blessings in trade?',
    options: { A: 'Honesty in trade', B: 'Silence', C: 'Isolation', D: 'Sleep' },
    correct: 'A',
    explanation: 'The Prophet ﷺ said: "The buyer and seller have the option to cancel until they part. If they are honest, their transaction is blessed; if they lie, the blessing is removed." (Bukhari, Muslim)',
  },
  {
    id: 'sn-020',
    category: 'sunnah',
    question: 'Which trait prevents entry into Paradise if left unchecked?',
    options: { A: 'Forgetfulness', B: 'Arrogance', C: 'Shyness', D: 'Fear' },
    correct: 'B',
    explanation: 'The Prophet ﷺ said: "No one with a grain of arrogance in his heart will enter Paradise." (Muslim) — arrogance is a spiritual barrier between the servant and Allah\'s mercy.',
  },
  {
    id: 'sn-021',
    category: 'sunnah',
    question: 'Which act is considered worship when performed with the right intention?',
    options: { A: 'Sleep', B: 'Walking', C: 'Eating with intention', D: 'Talking' },
    correct: 'C',
    explanation: 'The Prophet ﷺ taught that eating for the sake of strength to worship Allah transforms a mundane act into worship. Intention is what elevates daily life to devotion.',
  },
  {
    id: 'sn-022',
    category: 'sunnah',
    question: 'Which habit does the hadith say strengthens community bonds?',
    options: { A: 'Generosity', B: 'Isolation', C: 'Argument', D: 'Suspicion' },
    correct: 'A',
    explanation: 'The Prophet ﷺ encouraged giving gifts to increase love, visiting the sick, and feeding others — all forms of generosity that bind the Muslim community together.',
  },
  {
    id: 'sn-023',
    category: 'sunnah',
    question: 'The Prophet ﷺ emphasised that justice must be upheld even toward:',
    options: { A: 'Friends', B: 'Family', C: 'Leaders', D: 'Enemies' },
    correct: 'D',
    explanation: 'The Qur\'an commands: "Let not the hatred of a people prevent you from being just. Be just — that is nearer to Taqwa." (Al-Maidah 5:8) The Prophet ﷺ embodied this toward Quraysh.',
  },
  {
    id: 'sn-024',
    category: 'sunnah',
    question: 'Which behavior does the hadith warn leads to spiritual blindness?',
    options: { A: 'Knowledge', B: 'Patience', C: 'Arrogance', D: 'Gratitude' },
    correct: 'C',
    explanation: 'Arrogance blinds a person to truth. The Prophet ﷺ said arrogance means "rejecting truth and belittling people" — it closes the heart to guidance and self-improvement.',
  },
  {
    id: 'sn-025',
    category: 'sunnah',
    question: 'Which action brings divine assistance, according to hadith?',
    options: { A: 'Pride', B: 'Helping others', C: 'Isolation', D: 'Silence' },
    correct: 'B',
    explanation: 'The Prophet ﷺ said: "Allah helps the servant as long as the servant is helping his brother." (Muslim) — service to others is a direct means of receiving Allah\'s help.',
  },
]
