// Static Juz reference data (~2KB)
// Each Juz maps to its starting Surah name for display context
export const JUZ_DATA: { id: number; name: string; startSurah: string; startAyah: number }[] = [
  { id: 1, name: 'Alif Lam Mim', startSurah: 'Al-Fatiha', startAyah: 1 },
  { id: 2, name: 'Sayaqul', startSurah: 'Al-Baqarah', startAyah: 142 },
  { id: 3, name: 'Tilkar Rusul', startSurah: 'Al-Baqarah', startAyah: 253 },
  { id: 4, name: 'Lan Tanaloo', startSurah: "Ali 'Imran", startAyah: 93 },
  { id: 5, name: 'Wal Muhsanat', startSurah: 'An-Nisa', startAyah: 24 },
  { id: 6, name: 'La Yuhibbullah', startSurah: 'An-Nisa', startAyah: 148 },
  { id: 7, name: 'Wa Iza Samiu', startSurah: "Al-Ma'idah", startAyah: 83 },
  { id: 8, name: 'Wa Lau Annana', startSurah: "Al-An'am", startAyah: 111 },
  { id: 9, name: 'Qalal Malau', startSurah: "Al-A'raf", startAyah: 88 },
  { id: 10, name: "Wa A'lamu", startSurah: 'Al-Anfal', startAyah: 41 },
  { id: 11, name: 'Yatazeroon', startSurah: 'At-Tawbah', startAyah: 94 },
  { id: 12, name: 'Wa Mamin Dabbah', startSurah: 'Hud', startAyah: 6 },
  { id: 13, name: 'Wa Ma Ubarriu', startSurah: 'Yusuf', startAyah: 53 },
  { id: 14, name: 'Rubama', startSurah: 'Al-Hijr', startAyah: 1 },
  { id: 15, name: 'Subhanallazi', startSurah: 'Al-Isra', startAyah: 1 },
  { id: 16, name: 'Qal Alam', startSurah: 'Al-Kahf', startAyah: 75 },
  { id: 17, name: 'Iqtaraba', startSurah: 'Al-Anbiya', startAyah: 1 },
  { id: 18, name: 'Qad Aflaha', startSurah: "Al-Mu'minun", startAyah: 1 },
  { id: 19, name: 'Wa Qalallazina', startSurah: 'Al-Furqan', startAyah: 21 },
  { id: 20, name: 'Amman Khalaq', startSurah: 'An-Naml', startAyah: 56 },
  { id: 21, name: 'Utlu Ma Uhiya', startSurah: 'Al-Ankabut', startAyah: 46 },
  { id: 22, name: 'Wa Man Yaqnut', startSurah: 'Al-Ahzab', startAyah: 31 },
  { id: 23, name: 'Wa Mali', startSurah: 'Ya-Sin', startAyah: 28 },
  { id: 24, name: 'Faman Azlamu', startSurah: 'Az-Zumar', startAyah: 32 },
  { id: 25, name: 'Ilayhi Yuraddu', startSurah: 'Fussilat', startAyah: 47 },
  { id: 26, name: 'Ha Mim', startSurah: 'Al-Ahqaf', startAyah: 1 },
  { id: 27, name: 'Qala Fama Khatbukum', startSurah: 'Adh-Dhariyat', startAyah: 31 },
  { id: 28, name: 'Qad Samia Allah', startSurah: 'Al-Mujadila', startAyah: 1 },
  { id: 29, name: 'Tabarakallazi', startSurah: 'Al-Mulk', startAyah: 1 },
  { id: 30, name: 'Amma', startSurah: 'An-Naba', startAyah: 1 },
]
