export interface SurahData {
  id: number
  arabicName: string
  englishName: string
  transliteration: string
  revelationType: 'meccan' | 'medinan'
  verseCount: number
  juzStart: number // which Juz this surah begins in
}

export const SURAH_DATA: SurahData[] = [
  { id: 1, arabicName: 'الفاتحة', englishName: 'The Opening', transliteration: 'Al-Fatihah', revelationType: 'meccan', verseCount: 7, juzStart: 1 },
  { id: 2, arabicName: 'البقرة', englishName: 'The Cow', transliteration: 'Al-Baqarah', revelationType: 'medinan', verseCount: 286, juzStart: 1 },
  { id: 3, arabicName: 'آل عمران', englishName: 'Family of Imran', transliteration: "Ali 'Imran", revelationType: 'medinan', verseCount: 200, juzStart: 3 },
  { id: 4, arabicName: 'النساء', englishName: 'The Women', transliteration: 'An-Nisa', revelationType: 'medinan', verseCount: 176, juzStart: 4 },
  { id: 5, arabicName: 'المائدة', englishName: 'The Table Spread', transliteration: "Al-Ma'idah", revelationType: 'medinan', verseCount: 120, juzStart: 6 },
  { id: 6, arabicName: 'الأنعام', englishName: 'The Cattle', transliteration: "Al-An'am", revelationType: 'meccan', verseCount: 165, juzStart: 7 },
  { id: 7, arabicName: 'الأعراف', englishName: 'The Heights', transliteration: "Al-A'raf", revelationType: 'meccan', verseCount: 206, juzStart: 8 },
  { id: 8, arabicName: 'الأنفال', englishName: 'The Spoils of War', transliteration: 'Al-Anfal', revelationType: 'medinan', verseCount: 75, juzStart: 9 },
  { id: 9, arabicName: 'التوبة', englishName: 'The Repentance', transliteration: 'At-Tawbah', revelationType: 'medinan', verseCount: 129, juzStart: 10 },
  { id: 10, arabicName: 'يونس', englishName: 'Jonah', transliteration: 'Yunus', revelationType: 'meccan', verseCount: 109, juzStart: 11 },
  { id: 11, arabicName: 'هود', englishName: 'Hud', transliteration: 'Hud', revelationType: 'meccan', verseCount: 123, juzStart: 11 },
  { id: 12, arabicName: 'يوسف', englishName: 'Joseph', transliteration: 'Yusuf', revelationType: 'meccan', verseCount: 111, juzStart: 12 },
  { id: 13, arabicName: 'الرعد', englishName: 'The Thunder', transliteration: "Ar-Ra'd", revelationType: 'medinan', verseCount: 43, juzStart: 13 },
  { id: 14, arabicName: 'إبراهيم', englishName: 'Ibrahim', transliteration: 'Ibrahim', revelationType: 'meccan', verseCount: 52, juzStart: 13 },
  { id: 15, arabicName: 'الحجر', englishName: 'The Rocky Tract', transliteration: 'Al-Hijr', revelationType: 'meccan', verseCount: 99, juzStart: 14 },
  { id: 16, arabicName: 'النحل', englishName: 'The Bee', transliteration: 'An-Nahl', revelationType: 'meccan', verseCount: 128, juzStart: 14 },
  { id: 17, arabicName: 'الإسراء', englishName: 'The Night Journey', transliteration: 'Al-Isra', revelationType: 'meccan', verseCount: 111, juzStart: 15 },
  { id: 18, arabicName: 'الكهف', englishName: 'The Cave', transliteration: 'Al-Kahf', revelationType: 'meccan', verseCount: 110, juzStart: 15 },
  { id: 19, arabicName: 'مريم', englishName: 'Mary', transliteration: 'Maryam', revelationType: 'meccan', verseCount: 98, juzStart: 16 },
  { id: 20, arabicName: 'طه', englishName: 'Ta-Ha', transliteration: 'Ta-Ha', revelationType: 'meccan', verseCount: 135, juzStart: 16 },
  { id: 21, arabicName: 'الأنبياء', englishName: 'The Prophets', transliteration: 'Al-Anbiya', revelationType: 'meccan', verseCount: 112, juzStart: 17 },
  { id: 22, arabicName: 'الحج', englishName: 'The Pilgrimage', transliteration: 'Al-Hajj', revelationType: 'medinan', verseCount: 78, juzStart: 17 },
  { id: 23, arabicName: 'المؤمنون', englishName: 'The Believers', transliteration: "Al-Mu'minun", revelationType: 'meccan', verseCount: 118, juzStart: 18 },
  { id: 24, arabicName: 'النور', englishName: 'The Light', transliteration: 'An-Nur', revelationType: 'medinan', verseCount: 64, juzStart: 18 },
  { id: 25, arabicName: 'الفرقان', englishName: 'The Criterion', transliteration: 'Al-Furqan', revelationType: 'meccan', verseCount: 77, juzStart: 18 },
  { id: 26, arabicName: 'الشعراء', englishName: 'The Poets', transliteration: "Ash-Shu'ara", revelationType: 'meccan', verseCount: 227, juzStart: 19 },
  { id: 27, arabicName: 'النمل', englishName: 'The Ant', transliteration: 'An-Naml', revelationType: 'meccan', verseCount: 93, juzStart: 19 },
  { id: 28, arabicName: 'القصص', englishName: 'The Stories', transliteration: 'Al-Qasas', revelationType: 'meccan', verseCount: 88, juzStart: 20 },
  { id: 29, arabicName: 'العنكبوت', englishName: 'The Spider', transliteration: 'Al-Ankabut', revelationType: 'meccan', verseCount: 69, juzStart: 20 },
  { id: 30, arabicName: 'الروم', englishName: 'The Romans', transliteration: 'Ar-Rum', revelationType: 'meccan', verseCount: 60, juzStart: 21 },
  { id: 31, arabicName: 'لقمان', englishName: 'Luqman', transliteration: 'Luqman', revelationType: 'meccan', verseCount: 34, juzStart: 21 },
  { id: 32, arabicName: 'السجدة', englishName: 'The Prostration', transliteration: 'As-Sajdah', revelationType: 'meccan', verseCount: 30, juzStart: 21 },
  { id: 33, arabicName: 'الأحزاب', englishName: 'The Combined Forces', transliteration: 'Al-Ahzab', revelationType: 'medinan', verseCount: 73, juzStart: 21 },
  { id: 34, arabicName: 'سبأ', englishName: 'Sheba', transliteration: "Saba'", revelationType: 'meccan', verseCount: 54, juzStart: 22 },
  { id: 35, arabicName: 'فاطر', englishName: 'Originator', transliteration: 'Fatir', revelationType: 'meccan', verseCount: 45, juzStart: 22 },
  { id: 36, arabicName: 'يس', englishName: 'Ya Sin', transliteration: 'Ya-Sin', revelationType: 'meccan', verseCount: 83, juzStart: 22 },
  { id: 37, arabicName: 'الصافات', englishName: 'Those Who Set The Ranks', transliteration: 'As-Saffat', revelationType: 'meccan', verseCount: 182, juzStart: 23 },
  { id: 38, arabicName: 'ص', englishName: 'The Letter Sad', transliteration: 'Sad', revelationType: 'meccan', verseCount: 88, juzStart: 23 },
  { id: 39, arabicName: 'الزمر', englishName: 'The Troops', transliteration: 'Az-Zumar', revelationType: 'meccan', verseCount: 75, juzStart: 23 },
  { id: 40, arabicName: 'غافر', englishName: 'The Forgiver', transliteration: 'Ghafir', revelationType: 'meccan', verseCount: 85, juzStart: 24 },
  { id: 41, arabicName: 'فصلت', englishName: 'Explained in Detail', transliteration: 'Fussilat', revelationType: 'meccan', verseCount: 54, juzStart: 24 },
  { id: 42, arabicName: 'الشورى', englishName: 'The Consultation', transliteration: 'Ash-Shura', revelationType: 'meccan', verseCount: 53, juzStart: 25 },
  { id: 43, arabicName: 'الزخرف', englishName: 'The Ornaments of Gold', transliteration: 'Az-Zukhruf', revelationType: 'meccan', verseCount: 89, juzStart: 25 },
  { id: 44, arabicName: 'الدخان', englishName: 'The Smoke', transliteration: 'Ad-Dukhan', revelationType: 'meccan', verseCount: 59, juzStart: 25 },
  { id: 45, arabicName: 'الجاثية', englishName: 'The Crouching', transliteration: 'Al-Jathiyah', revelationType: 'meccan', verseCount: 37, juzStart: 25 },
  { id: 46, arabicName: 'الأحقاف', englishName: 'The Wind-Curved Sandhills', transliteration: 'Al-Ahqaf', revelationType: 'meccan', verseCount: 35, juzStart: 26 },
  { id: 47, arabicName: 'محمد', englishName: 'Muhammad', transliteration: 'Muhammad', revelationType: 'medinan', verseCount: 38, juzStart: 26 },
  { id: 48, arabicName: 'الفتح', englishName: 'The Victory', transliteration: 'Al-Fath', revelationType: 'medinan', verseCount: 29, juzStart: 26 },
  { id: 49, arabicName: 'الحجرات', englishName: 'The Rooms', transliteration: 'Al-Hujurat', revelationType: 'medinan', verseCount: 18, juzStart: 26 },
  { id: 50, arabicName: 'ق', englishName: 'The Letter Qaf', transliteration: 'Qaf', revelationType: 'meccan', verseCount: 45, juzStart: 26 },
  { id: 51, arabicName: 'الذاريات', englishName: 'The Winnowing Winds', transliteration: 'Adh-Dhariyat', revelationType: 'meccan', verseCount: 60, juzStart: 26 },
  { id: 52, arabicName: 'الطور', englishName: 'The Mount', transliteration: 'At-Tur', revelationType: 'meccan', verseCount: 49, juzStart: 27 },
  { id: 53, arabicName: 'النجم', englishName: 'The Star', transliteration: 'An-Najm', revelationType: 'meccan', verseCount: 62, juzStart: 27 },
  { id: 54, arabicName: 'القمر', englishName: 'The Moon', transliteration: 'Al-Qamar', revelationType: 'meccan', verseCount: 55, juzStart: 27 },
  { id: 55, arabicName: 'الرحمن', englishName: 'The Beneficent', transliteration: 'Ar-Rahman', revelationType: 'medinan', verseCount: 78, juzStart: 27 },
  { id: 56, arabicName: 'الواقعة', englishName: 'The Inevitable', transliteration: "Al-Waqi'ah", revelationType: 'meccan', verseCount: 96, juzStart: 27 },
  { id: 57, arabicName: 'الحديد', englishName: 'The Iron', transliteration: 'Al-Hadid', revelationType: 'medinan', verseCount: 29, juzStart: 27 },
  { id: 58, arabicName: 'المجادلة', englishName: 'She That Disputeth', transliteration: 'Al-Mujadila', revelationType: 'medinan', verseCount: 22, juzStart: 28 },
  { id: 59, arabicName: 'الحشر', englishName: 'The Exile', transliteration: 'Al-Hashr', revelationType: 'medinan', verseCount: 24, juzStart: 28 },
  { id: 60, arabicName: 'الممتحنة', englishName: 'She That Is To Be Examined', transliteration: 'Al-Mumtahanah', revelationType: 'medinan', verseCount: 13, juzStart: 28 },
  { id: 61, arabicName: 'الصف', englishName: 'The Ranks', transliteration: 'As-Saff', revelationType: 'medinan', verseCount: 14, juzStart: 28 },
  { id: 62, arabicName: 'الجمعة', englishName: 'Friday', transliteration: "Al-Jumu'ah", revelationType: 'medinan', verseCount: 11, juzStart: 28 },
  { id: 63, arabicName: 'المنافقون', englishName: 'The Hypocrites', transliteration: 'Al-Munafiqun', revelationType: 'medinan', verseCount: 11, juzStart: 28 },
  { id: 64, arabicName: 'التغابن', englishName: 'Mutual Disillusion', transliteration: 'At-Taghabun', revelationType: 'medinan', verseCount: 18, juzStart: 28 },
  { id: 65, arabicName: 'الطلاق', englishName: 'Divorce', transliteration: 'At-Talaq', revelationType: 'medinan', verseCount: 12, juzStart: 28 },
  { id: 66, arabicName: 'التحريم', englishName: 'The Prohibition', transliteration: 'At-Tahrim', revelationType: 'medinan', verseCount: 12, juzStart: 28 },
  { id: 67, arabicName: 'الملك', englishName: 'The Sovereignty', transliteration: 'Al-Mulk', revelationType: 'meccan', verseCount: 30, juzStart: 29 },
  { id: 68, arabicName: 'القلم', englishName: 'The Pen', transliteration: 'Al-Qalam', revelationType: 'meccan', verseCount: 52, juzStart: 29 },
  { id: 69, arabicName: 'الحاقة', englishName: 'The Reality', transliteration: 'Al-Haqqah', revelationType: 'meccan', verseCount: 52, juzStart: 29 },
  { id: 70, arabicName: 'المعارج', englishName: 'The Ascending Stairways', transliteration: "Al-Ma'arij", revelationType: 'meccan', verseCount: 44, juzStart: 29 },
  { id: 71, arabicName: 'نوح', englishName: 'Noah', transliteration: 'Nuh', revelationType: 'meccan', verseCount: 28, juzStart: 29 },
  { id: 72, arabicName: 'الجن', englishName: 'The Jinn', transliteration: 'Al-Jinn', revelationType: 'meccan', verseCount: 28, juzStart: 29 },
  { id: 73, arabicName: 'المزمل', englishName: 'The Enshrouded One', transliteration: 'Al-Muzzammil', revelationType: 'meccan', verseCount: 20, juzStart: 29 },
  { id: 74, arabicName: 'المدثر', englishName: 'The Cloaked One', transliteration: 'Al-Muddaththir', revelationType: 'meccan', verseCount: 56, juzStart: 29 },
  { id: 75, arabicName: 'القيامة', englishName: 'The Resurrection', transliteration: 'Al-Qiyamah', revelationType: 'meccan', verseCount: 40, juzStart: 29 },
  { id: 76, arabicName: 'الإنسان', englishName: 'The Man', transliteration: 'Al-Insan', revelationType: 'medinan', verseCount: 31, juzStart: 29 },
  { id: 77, arabicName: 'المرسلات', englishName: 'The Emissaries', transliteration: 'Al-Mursalat', revelationType: 'meccan', verseCount: 50, juzStart: 29 },
  { id: 78, arabicName: 'النبأ', englishName: 'The Tidings', transliteration: 'An-Naba', revelationType: 'meccan', verseCount: 40, juzStart: 30 },
  { id: 79, arabicName: 'النازعات', englishName: 'Those Who Drag Forth', transliteration: "An-Nazi'at", revelationType: 'meccan', verseCount: 46, juzStart: 30 },
  { id: 80, arabicName: 'عبس', englishName: 'He Frowned', transliteration: 'Abasa', revelationType: 'meccan', verseCount: 42, juzStart: 30 },
  { id: 81, arabicName: 'التكوير', englishName: 'The Overthrowing', transliteration: 'At-Takwir', revelationType: 'meccan', verseCount: 29, juzStart: 30 },
  { id: 82, arabicName: 'الانفطار', englishName: 'The Cleaving', transliteration: 'Al-Infitar', revelationType: 'meccan', verseCount: 19, juzStart: 30 },
  { id: 83, arabicName: 'المطففين', englishName: 'The Defrauding', transliteration: 'Al-Mutaffifin', revelationType: 'meccan', verseCount: 36, juzStart: 30 },
  { id: 84, arabicName: 'الانشقاق', englishName: 'The Sundering', transliteration: 'Al-Inshiqaq', revelationType: 'meccan', verseCount: 25, juzStart: 30 },
  { id: 85, arabicName: 'البروج', englishName: 'The Mansions of the Stars', transliteration: 'Al-Buruj', revelationType: 'meccan', verseCount: 22, juzStart: 30 },
  { id: 86, arabicName: 'الطارق', englishName: 'The Nightcomer', transliteration: 'At-Tariq', revelationType: 'meccan', verseCount: 17, juzStart: 30 },
  { id: 87, arabicName: 'الأعلى', englishName: 'The Most High', transliteration: "Al-A'la", revelationType: 'meccan', verseCount: 19, juzStart: 30 },
  { id: 88, arabicName: 'الغاشية', englishName: 'The Overwhelming', transliteration: 'Al-Ghashiyah', revelationType: 'meccan', verseCount: 26, juzStart: 30 },
  { id: 89, arabicName: 'الفجر', englishName: 'The Dawn', transliteration: 'Al-Fajr', revelationType: 'meccan', verseCount: 30, juzStart: 30 },
  { id: 90, arabicName: 'البلد', englishName: 'The City', transliteration: 'Al-Balad', revelationType: 'meccan', verseCount: 20, juzStart: 30 },
  { id: 91, arabicName: 'الشمس', englishName: 'The Sun', transliteration: 'Ash-Shams', revelationType: 'meccan', verseCount: 15, juzStart: 30 },
  { id: 92, arabicName: 'الليل', englishName: 'The Night', transliteration: 'Al-Layl', revelationType: 'meccan', verseCount: 21, juzStart: 30 },
  { id: 93, arabicName: 'الضحى', englishName: 'The Morning Hours', transliteration: 'Ad-Duha', revelationType: 'meccan', verseCount: 11, juzStart: 30 },
  { id: 94, arabicName: 'الشرح', englishName: 'The Relief', transliteration: 'Ash-Sharh', revelationType: 'meccan', verseCount: 8, juzStart: 30 },
  { id: 95, arabicName: 'التين', englishName: 'The Fig', transliteration: 'At-Tin', revelationType: 'meccan', verseCount: 8, juzStart: 30 },
  { id: 96, arabicName: 'العلق', englishName: 'The Clot', transliteration: "Al-'Alaq", revelationType: 'meccan', verseCount: 19, juzStart: 30 },
  { id: 97, arabicName: 'القدر', englishName: 'The Power', transliteration: 'Al-Qadr', revelationType: 'meccan', verseCount: 5, juzStart: 30 },
  { id: 98, arabicName: 'البينة', englishName: 'The Clear Proof', transliteration: 'Al-Bayyinah', revelationType: 'medinan', verseCount: 8, juzStart: 30 },
  { id: 99, arabicName: 'الزلزلة', englishName: 'The Earthquake', transliteration: 'Az-Zalzalah', revelationType: 'medinan', verseCount: 8, juzStart: 30 },
  { id: 100, arabicName: 'العاديات', englishName: 'The Coursers', transliteration: "Al-'Adiyat", revelationType: 'meccan', verseCount: 11, juzStart: 30 },
  { id: 101, arabicName: 'القارعة', englishName: 'The Calamity', transliteration: "Al-Qari'ah", revelationType: 'meccan', verseCount: 11, juzStart: 30 },
  { id: 102, arabicName: 'التكاثر', englishName: 'The Rivalry in World Increase', transliteration: 'At-Takathur', revelationType: 'meccan', verseCount: 8, juzStart: 30 },
  { id: 103, arabicName: 'العصر', englishName: 'The Declining Day', transliteration: "Al-'Asr", revelationType: 'meccan', verseCount: 3, juzStart: 30 },
  { id: 104, arabicName: 'الهمزة', englishName: 'The Traducer', transliteration: 'Al-Humazah', revelationType: 'meccan', verseCount: 9, juzStart: 30 },
  { id: 105, arabicName: 'الفيل', englishName: 'The Elephant', transliteration: 'Al-Fil', revelationType: 'meccan', verseCount: 5, juzStart: 30 },
  { id: 106, arabicName: 'قريش', englishName: 'Quraysh', transliteration: 'Quraysh', revelationType: 'meccan', verseCount: 4, juzStart: 30 },
  { id: 107, arabicName: 'الماعون', englishName: 'The Small Kindnesses', transliteration: "Al-Ma'un", revelationType: 'meccan', verseCount: 7, juzStart: 30 },
  { id: 108, arabicName: 'الكوثر', englishName: 'The Abundance', transliteration: 'Al-Kawthar', revelationType: 'meccan', verseCount: 3, juzStart: 30 },
  { id: 109, arabicName: 'الكافرون', englishName: 'The Disbelievers', transliteration: 'Al-Kafirun', revelationType: 'meccan', verseCount: 6, juzStart: 30 },
  { id: 110, arabicName: 'النصر', englishName: 'The Divine Support', transliteration: 'An-Nasr', revelationType: 'medinan', verseCount: 3, juzStart: 30 },
  { id: 111, arabicName: 'المسد', englishName: 'The Palm Fibre', transliteration: 'Al-Masad', revelationType: 'meccan', verseCount: 5, juzStart: 30 },
  { id: 112, arabicName: 'الإخلاص', englishName: 'The Sincerity', transliteration: 'Al-Ikhlas', revelationType: 'meccan', verseCount: 4, juzStart: 30 },
  { id: 113, arabicName: 'الفلق', englishName: 'The Daybreak', transliteration: 'Al-Falaq', revelationType: 'meccan', verseCount: 5, juzStart: 30 },
  { id: 114, arabicName: 'الناس', englishName: 'Mankind', transliteration: 'An-Nas', revelationType: 'meccan', verseCount: 6, juzStart: 30 },
]
